/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.two.player.wordle;

import java.awt.Color;
import javax.swing.JOptionPane;
import java.util.Scanner;
import java.util.Random;
import java.io.File;
import java.io.FileNotFoundException;

/**
 *
 * @author Joshua
 */
public class MainGame_Versus extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainGame_Versus.class.getName());

    /**
     * Creates new form MainGame_Interface
     */
    private int player1_Attempts = 5; // IF ADDING MOR ATTEMPTS DO NOT FORGET TO CHNAGE THIS 
    private int player2_Attempts = 5; 
    private String player1Word = ""; // global variable for the word to be set for player 1 
    private String player2Word = "";  // global variable for the word to be set for player 2 
    private int u_Score_player_1 = 0;
    private int u_Score_player_2 = 0;

    private boolean player1_Finished = false; 
    private boolean player2_Finished = false;
   
    public MainGame_Versus() {
        initComponents();
    }
    
    
    public MainGame_Versus(String player1Word, String player2Word) {
        initComponents();
        this.player1Word = player1Word;
        this.player2Word = player2Word;
        attempt_Number_p1.setText("Attempt Left - 5");
        attempt_Number_p2.setText("Attempt Left - 5");
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        User_input_p1 = new javax.swing.JTextField();
        User_input_confirm_P1 = new javax.swing.JButton();
        a1_l4_p1 = new javax.swing.JLabel();
        a1_l1_p1 = new javax.swing.JLabel();
        a1_l2_p1 = new javax.swing.JLabel();
        a1_l3_p1 = new javax.swing.JLabel();
        a2_l1_p1 = new javax.swing.JLabel();
        a2_l2_p1 = new javax.swing.JLabel();
        a2_l3_p1 = new javax.swing.JLabel();
        a2_l4_p1 = new javax.swing.JLabel();
        a3_l1_p1 = new javax.swing.JLabel();
        a3_l2_p1 = new javax.swing.JLabel();
        a3_l3_p1 = new javax.swing.JLabel();
        a3_l4_p1 = new javax.swing.JLabel();
        a4_l1_p1 = new javax.swing.JLabel();
        a4_l2_p1 = new javax.swing.JLabel();
        a4_l3_p1 = new javax.swing.JLabel();
        a4_l4_p1 = new javax.swing.JLabel();
        title_Game = new javax.swing.JLabel();
        attempt_Number_p1 = new javax.swing.JLabel();
        back_Button = new javax.swing.JLabel();
        a5_l1_p1 = new javax.swing.JLabel();
        a5_l2_p1 = new javax.swing.JLabel();
        a5_l3_p1 = new javax.swing.JLabel();
        a5_l4_p1 = new javax.swing.JLabel();
        User_input_p2 = new javax.swing.JTextField();
        User_input_confirm_P2 = new javax.swing.JButton();
        a1_l4_p2 = new javax.swing.JLabel();
        a1_l1_p2 = new javax.swing.JLabel();
        a1_l2_p2 = new javax.swing.JLabel();
        a1_l3_p2 = new javax.swing.JLabel();
        a2_l1_p2 = new javax.swing.JLabel();
        a2_l2_p2 = new javax.swing.JLabel();
        a2_l3_p2 = new javax.swing.JLabel();
        a2_l4_p2 = new javax.swing.JLabel();
        a3_l1_p2 = new javax.swing.JLabel();
        a3_l2_p2 = new javax.swing.JLabel();
        a3_l3_p2 = new javax.swing.JLabel();
        a3_l4_p2 = new javax.swing.JLabel();
        a4_l1_p2 = new javax.swing.JLabel();
        a4_l2_p2 = new javax.swing.JLabel();
        a4_l3_p2 = new javax.swing.JLabel();
        a4_l4_p2 = new javax.swing.JLabel();
        attempt_Number_p2 = new javax.swing.JLabel();
        a5_l1_p2 = new javax.swing.JLabel();
        a5_l2_p2 = new javax.swing.JLabel();
        a5_l3_p2 = new javax.swing.JLabel();
        a5_l4_p2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(240, 234, 214));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(240, 234, 214));
        setSize(new java.awt.Dimension(400, 600));

        jPanel1.setBackground(new java.awt.Color(119, 136, 115));
        jPanel1.setForeground(new java.awt.Color(119, 136, 115));
        jPanel1.setToolTipText("");
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 600));

        User_input_p1.setBackground(new java.awt.Color(241, 243, 224));
        User_input_p1.setFont(new java.awt.Font("AirbusDisp2", 1, 12)); // NOI18N
        User_input_p1.setForeground(new java.awt.Color(119, 136, 115));
        User_input_p1.setText("ENTER A 4 LETTER WORD");
        User_input_p1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        User_input_p1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                User_input_p1ActionPerformed(evt);
            }
        });

        User_input_confirm_P1.setBackground(new java.awt.Color(210, 220, 182));
        User_input_confirm_P1.setFont(new java.awt.Font("AirbusDisp2", 1, 14)); // NOI18N
        User_input_confirm_P1.setForeground(new java.awt.Color(119, 136, 115));
        User_input_confirm_P1.setText("Confirm");
        User_input_confirm_P1.setAlignmentY(0.0F);
        User_input_confirm_P1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        User_input_confirm_P1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        User_input_confirm_P1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                User_input_confirm_P1ActionPerformed(evt);
            }
        });

        a1_l4_p1.setBackground(new java.awt.Color(161, 188, 152));
        a1_l4_p1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a1_l4_p1.setForeground(new java.awt.Color(241, 243, 224));
        a1_l4_p1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a1_l4_p1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a1_l4_p1.setOpaque(true);

        a1_l1_p1.setBackground(new java.awt.Color(161, 188, 152));
        a1_l1_p1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a1_l1_p1.setForeground(new java.awt.Color(241, 243, 224));
        a1_l1_p1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a1_l1_p1.setToolTipText("");
        a1_l1_p1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a1_l1_p1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        a1_l1_p1.setInheritsPopupMenu(false);
        a1_l1_p1.setOpaque(true);

        a1_l2_p1.setBackground(new java.awt.Color(161, 188, 152));
        a1_l2_p1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a1_l2_p1.setForeground(new java.awt.Color(241, 243, 224));
        a1_l2_p1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a1_l2_p1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a1_l2_p1.setOpaque(true);

        a1_l3_p1.setBackground(new java.awt.Color(161, 188, 152));
        a1_l3_p1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a1_l3_p1.setForeground(new java.awt.Color(241, 243, 224));
        a1_l3_p1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a1_l3_p1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a1_l3_p1.setOpaque(true);

        a2_l1_p1.setBackground(new java.awt.Color(161, 188, 152));
        a2_l1_p1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a2_l1_p1.setForeground(new java.awt.Color(241, 243, 224));
        a2_l1_p1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a2_l1_p1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a2_l1_p1.setOpaque(true);

        a2_l2_p1.setBackground(new java.awt.Color(161, 188, 152));
        a2_l2_p1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a2_l2_p1.setForeground(new java.awt.Color(241, 243, 224));
        a2_l2_p1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a2_l2_p1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a2_l2_p1.setOpaque(true);

        a2_l3_p1.setBackground(new java.awt.Color(161, 188, 152));
        a2_l3_p1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a2_l3_p1.setForeground(new java.awt.Color(241, 243, 224));
        a2_l3_p1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a2_l3_p1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a2_l3_p1.setOpaque(true);

        a2_l4_p1.setBackground(new java.awt.Color(161, 188, 152));
        a2_l4_p1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a2_l4_p1.setForeground(new java.awt.Color(241, 243, 224));
        a2_l4_p1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a2_l4_p1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a2_l4_p1.setOpaque(true);

        a3_l1_p1.setBackground(new java.awt.Color(161, 188, 152));
        a3_l1_p1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a3_l1_p1.setForeground(new java.awt.Color(241, 243, 224));
        a3_l1_p1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a3_l1_p1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a3_l1_p1.setOpaque(true);

        a3_l2_p1.setBackground(new java.awt.Color(161, 188, 152));
        a3_l2_p1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a3_l2_p1.setForeground(new java.awt.Color(241, 243, 224));
        a3_l2_p1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a3_l2_p1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a3_l2_p1.setOpaque(true);

        a3_l3_p1.setBackground(new java.awt.Color(161, 188, 152));
        a3_l3_p1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a3_l3_p1.setForeground(new java.awt.Color(241, 243, 224));
        a3_l3_p1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a3_l3_p1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a3_l3_p1.setOpaque(true);

        a3_l4_p1.setBackground(new java.awt.Color(161, 188, 152));
        a3_l4_p1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a3_l4_p1.setForeground(new java.awt.Color(241, 243, 224));
        a3_l4_p1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a3_l4_p1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a3_l4_p1.setOpaque(true);

        a4_l1_p1.setBackground(new java.awt.Color(161, 188, 152));
        a4_l1_p1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a4_l1_p1.setForeground(new java.awt.Color(241, 243, 224));
        a4_l1_p1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a4_l1_p1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a4_l1_p1.setOpaque(true);

        a4_l2_p1.setBackground(new java.awt.Color(161, 188, 152));
        a4_l2_p1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a4_l2_p1.setForeground(new java.awt.Color(241, 243, 224));
        a4_l2_p1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a4_l2_p1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a4_l2_p1.setOpaque(true);

        a4_l3_p1.setBackground(new java.awt.Color(161, 188, 152));
        a4_l3_p1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a4_l3_p1.setForeground(new java.awt.Color(241, 243, 224));
        a4_l3_p1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a4_l3_p1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a4_l3_p1.setOpaque(true);

        a4_l4_p1.setBackground(new java.awt.Color(161, 188, 152));
        a4_l4_p1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a4_l4_p1.setForeground(new java.awt.Color(241, 243, 224));
        a4_l4_p1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a4_l4_p1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a4_l4_p1.setOpaque(true);

        title_Game.setBackground(new java.awt.Color(49, 54, 71));
        title_Game.setFont(new java.awt.Font("Modern No. 20", 0, 36)); // NOI18N
        title_Game.setForeground(new java.awt.Color(210, 220, 182));
        title_Game.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title_Game.setText("WORDLE-OFF");

        attempt_Number_p1.setFont(new java.awt.Font("AirbusDisp2", 0, 14)); // NOI18N
        attempt_Number_p1.setForeground(new java.awt.Color(210, 220, 182));
        attempt_Number_p1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        back_Button.setFont(new java.awt.Font("AirbusDisp2", 0, 12)); // NOI18N
        back_Button.setForeground(new java.awt.Color(210, 220, 182));
        back_Button.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        back_Button.setText("Back");
        back_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back_ButtonMouseClicked(evt);
            }
        });

        a5_l1_p1.setBackground(new java.awt.Color(161, 188, 152));
        a5_l1_p1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a5_l1_p1.setForeground(new java.awt.Color(241, 243, 224));
        a5_l1_p1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a5_l1_p1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a5_l1_p1.setOpaque(true);

        a5_l2_p1.setBackground(new java.awt.Color(161, 188, 152));
        a5_l2_p1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a5_l2_p1.setForeground(new java.awt.Color(241, 243, 224));
        a5_l2_p1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a5_l2_p1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a5_l2_p1.setOpaque(true);

        a5_l3_p1.setBackground(new java.awt.Color(161, 188, 152));
        a5_l3_p1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a5_l3_p1.setForeground(new java.awt.Color(241, 243, 224));
        a5_l3_p1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a5_l3_p1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a5_l3_p1.setOpaque(true);

        a5_l4_p1.setBackground(new java.awt.Color(161, 188, 152));
        a5_l4_p1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a5_l4_p1.setForeground(new java.awt.Color(241, 243, 224));
        a5_l4_p1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a5_l4_p1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a5_l4_p1.setOpaque(true);

        User_input_p2.setBackground(new java.awt.Color(241, 243, 224));
        User_input_p2.setFont(new java.awt.Font("AirbusDisp2", 1, 12)); // NOI18N
        User_input_p2.setForeground(new java.awt.Color(119, 136, 115));
        User_input_p2.setText("ENTER A 4 LETTER WORD");
        User_input_p2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        User_input_p2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                User_input_p2ActionPerformed(evt);
            }
        });

        User_input_confirm_P2.setBackground(new java.awt.Color(210, 220, 182));
        User_input_confirm_P2.setFont(new java.awt.Font("AirbusDisp2", 1, 14)); // NOI18N
        User_input_confirm_P2.setForeground(new java.awt.Color(119, 136, 115));
        User_input_confirm_P2.setText("Confirm");
        User_input_confirm_P2.setAlignmentY(0.0F);
        User_input_confirm_P2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        User_input_confirm_P2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        User_input_confirm_P2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                User_input_confirm_P2ActionPerformed(evt);
            }
        });

        a1_l4_p2.setBackground(new java.awt.Color(161, 188, 152));
        a1_l4_p2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a1_l4_p2.setForeground(new java.awt.Color(241, 243, 224));
        a1_l4_p2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a1_l4_p2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a1_l4_p2.setOpaque(true);

        a1_l1_p2.setBackground(new java.awt.Color(161, 188, 152));
        a1_l1_p2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a1_l1_p2.setForeground(new java.awt.Color(241, 243, 224));
        a1_l1_p2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a1_l1_p2.setToolTipText("");
        a1_l1_p2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a1_l1_p2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        a1_l1_p2.setInheritsPopupMenu(false);
        a1_l1_p2.setOpaque(true);

        a1_l2_p2.setBackground(new java.awt.Color(161, 188, 152));
        a1_l2_p2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a1_l2_p2.setForeground(new java.awt.Color(241, 243, 224));
        a1_l2_p2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a1_l2_p2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a1_l2_p2.setOpaque(true);

        a1_l3_p2.setBackground(new java.awt.Color(161, 188, 152));
        a1_l3_p2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a1_l3_p2.setForeground(new java.awt.Color(241, 243, 224));
        a1_l3_p2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a1_l3_p2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a1_l3_p2.setOpaque(true);

        a2_l1_p2.setBackground(new java.awt.Color(161, 188, 152));
        a2_l1_p2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a2_l1_p2.setForeground(new java.awt.Color(241, 243, 224));
        a2_l1_p2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a2_l1_p2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a2_l1_p2.setOpaque(true);

        a2_l2_p2.setBackground(new java.awt.Color(161, 188, 152));
        a2_l2_p2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a2_l2_p2.setForeground(new java.awt.Color(241, 243, 224));
        a2_l2_p2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a2_l2_p2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a2_l2_p2.setOpaque(true);

        a2_l3_p2.setBackground(new java.awt.Color(161, 188, 152));
        a2_l3_p2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a2_l3_p2.setForeground(new java.awt.Color(241, 243, 224));
        a2_l3_p2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a2_l3_p2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a2_l3_p2.setOpaque(true);

        a2_l4_p2.setBackground(new java.awt.Color(161, 188, 152));
        a2_l4_p2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a2_l4_p2.setForeground(new java.awt.Color(241, 243, 224));
        a2_l4_p2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a2_l4_p2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a2_l4_p2.setOpaque(true);

        a3_l1_p2.setBackground(new java.awt.Color(161, 188, 152));
        a3_l1_p2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a3_l1_p2.setForeground(new java.awt.Color(241, 243, 224));
        a3_l1_p2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a3_l1_p2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a3_l1_p2.setOpaque(true);

        a3_l2_p2.setBackground(new java.awt.Color(161, 188, 152));
        a3_l2_p2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a3_l2_p2.setForeground(new java.awt.Color(241, 243, 224));
        a3_l2_p2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a3_l2_p2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a3_l2_p2.setOpaque(true);

        a3_l3_p2.setBackground(new java.awt.Color(161, 188, 152));
        a3_l3_p2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a3_l3_p2.setForeground(new java.awt.Color(241, 243, 224));
        a3_l3_p2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a3_l3_p2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a3_l3_p2.setOpaque(true);

        a3_l4_p2.setBackground(new java.awt.Color(161, 188, 152));
        a3_l4_p2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a3_l4_p2.setForeground(new java.awt.Color(241, 243, 224));
        a3_l4_p2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a3_l4_p2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a3_l4_p2.setOpaque(true);

        a4_l1_p2.setBackground(new java.awt.Color(161, 188, 152));
        a4_l1_p2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a4_l1_p2.setForeground(new java.awt.Color(241, 243, 224));
        a4_l1_p2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a4_l1_p2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a4_l1_p2.setOpaque(true);

        a4_l2_p2.setBackground(new java.awt.Color(161, 188, 152));
        a4_l2_p2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a4_l2_p2.setForeground(new java.awt.Color(241, 243, 224));
        a4_l2_p2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a4_l2_p2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a4_l2_p2.setOpaque(true);

        a4_l3_p2.setBackground(new java.awt.Color(161, 188, 152));
        a4_l3_p2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a4_l3_p2.setForeground(new java.awt.Color(241, 243, 224));
        a4_l3_p2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a4_l3_p2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a4_l3_p2.setOpaque(true);

        a4_l4_p2.setBackground(new java.awt.Color(161, 188, 152));
        a4_l4_p2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a4_l4_p2.setForeground(new java.awt.Color(241, 243, 224));
        a4_l4_p2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a4_l4_p2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a4_l4_p2.setOpaque(true);

        attempt_Number_p2.setFont(new java.awt.Font("AirbusDisp2", 0, 14)); // NOI18N
        attempt_Number_p2.setForeground(new java.awt.Color(210, 220, 182));
        attempt_Number_p2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        a5_l1_p2.setBackground(new java.awt.Color(161, 188, 152));
        a5_l1_p2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a5_l1_p2.setForeground(new java.awt.Color(241, 243, 224));
        a5_l1_p2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a5_l1_p2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a5_l1_p2.setOpaque(true);

        a5_l2_p2.setBackground(new java.awt.Color(161, 188, 152));
        a5_l2_p2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a5_l2_p2.setForeground(new java.awt.Color(241, 243, 224));
        a5_l2_p2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a5_l2_p2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a5_l2_p2.setOpaque(true);

        a5_l3_p2.setBackground(new java.awt.Color(161, 188, 152));
        a5_l3_p2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a5_l3_p2.setForeground(new java.awt.Color(241, 243, 224));
        a5_l3_p2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a5_l3_p2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a5_l3_p2.setOpaque(true);

        a5_l4_p2.setBackground(new java.awt.Color(161, 188, 152));
        a5_l4_p2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a5_l4_p2.setForeground(new java.awt.Color(241, 243, 224));
        a5_l4_p2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a5_l4_p2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a5_l4_p2.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(User_input_confirm_P1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(attempt_Number_p1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(a3_l1_p1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(a3_l2_p1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(a3_l3_p1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(a3_l4_p1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(a2_l1_p1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(a2_l2_p1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(a2_l3_p1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(a2_l4_p1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(a1_l1_p1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(a1_l2_p1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(a1_l3_p1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(a1_l4_p1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(a4_l1_p1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(a4_l2_p1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(a4_l3_p1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(a4_l4_p1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(a5_l1_p1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(a5_l2_p1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(a5_l3_p1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(a5_l4_p1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(User_input_p1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(attempt_Number_p2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(a3_l1_p2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(a3_l2_p2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(a3_l3_p2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(a3_l4_p2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(a2_l1_p2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(a2_l2_p2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(a2_l3_p2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(a2_l4_p2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(a1_l1_p2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(a1_l2_p2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(a1_l3_p2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(a1_l4_p2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(a4_l1_p2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(a4_l2_p2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(a4_l3_p2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(a4_l4_p2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(a5_l1_p2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(a5_l2_p2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(a5_l3_p2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(a5_l4_p2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(User_input_p2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(139, 139, 139))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(back_Button)
                        .addGap(96, 96, 96)
                        .addComponent(User_input_confirm_P2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(183, 183, 183))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(253, 253, 253)
                .addComponent(title_Game, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title_Game, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(a1_l1_p2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(a1_l2_p2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(a1_l4_p2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(a1_l3_p2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(a2_l1_p2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(a2_l2_p2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(a2_l4_p2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(a2_l3_p2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(a3_l1_p2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(a3_l2_p2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(a3_l4_p2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(a3_l3_p2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(a4_l1_p2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(a4_l2_p2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(a4_l4_p2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(a4_l3_p2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(a5_l1_p2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(a5_l2_p2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(a5_l4_p2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(a5_l3_p2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(User_input_p2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(attempt_Number_p2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(User_input_confirm_P2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(back_Button)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(a1_l1_p1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(a1_l2_p1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(a1_l4_p1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(a1_l3_p1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(a2_l1_p1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(a2_l2_p1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(a2_l4_p1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(a2_l3_p1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(a3_l1_p1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(a3_l2_p1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(a3_l4_p1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(a3_l3_p1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(a4_l1_p1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(a4_l2_p1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(a4_l4_p1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(a4_l3_p1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(a5_l1_p1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(a5_l2_p1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(a5_l4_p1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(a5_l3_p1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(User_input_p1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(attempt_Number_p1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(User_input_confirm_P1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(99, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    
    
    // back button
    private void back_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_ButtonMouseClicked
        MainGame_Menu btn_back = new MainGame_Menu( );
        if(player1_Attempts != 0){
            int dialog_Result = JOptionPane.showConfirmDialog(null, "All porgress will be lost if you go back", "Go Back?", JOptionPane.YES_NO_OPTION);
            if(dialog_Result == JOptionPane.YES_OPTION){
                dispose();
                btn_back.setVisible(true);
            } else if(dialog_Result == JOptionPane.NO_OPTION){
                //do nothing
            }
        } else if (player1_Attempts == 0){
            dispose();
            btn_back.setVisible(true);

        }

    }//GEN-LAST:event_back_ButtonMouseClicked

    private void User_input_confirm_P1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_User_input_confirm_P1ActionPerformed
        if (player1_Finished) {
            return;
        }
        String user_Input_Word  = "";
        user_Input_Word = User_input_p1.getText().toLowerCase();

        String []Conv_user_Input_Word = user_Input_Word.split("");

        if(user_Input_Word.length() != 4){
            JOptionPane.showMessageDialog(null,"The word should be made of 4 Letters");
        } else {
            int []cpuWord_letterflag = {0,0,0,0};
            int []userInput_letterflag = {0,0,0,0};
            switch (player1_Attempts) {
                case 5:
                attempt_Number_p1.setText("Attempt Left - 4");
                a1_l1_p1.setText(Conv_user_Input_Word[0]);
                a1_l1_p1.setBackground(Color.gray);

                a1_l2_p1.setText(Conv_user_Input_Word[1]);
                a1_l2_p1.setBackground(Color.gray);

                a1_l3_p1.setText(Conv_user_Input_Word[2]);
                a1_l3_p1.setBackground(Color.gray);

                a1_l4_p1.setText(Conv_user_Input_Word[3]);
                a1_l4_p1.setBackground(Color.gray);

                for (int i = 0; i < 4; i++) {
                    if(user_Input_Word.charAt(i) == player1Word.charAt(i)){
                        switch (i) {
                            case 0: a1_l1_p1.setBackground(Color.GREEN);
                            break;
                            case 1: a1_l2_p1.setBackground(Color.GREEN);
                            break;
                            case 2: a1_l3_p1.setBackground(Color.GREEN);
                            break;
                            case 3: a1_l4_p1.setBackground(Color.GREEN);
                            break;
                        }
                        cpuWord_letterflag[i] = 1;
                        userInput_letterflag[i] = 1;
                    }
                }

                for (int i = 0; i < 4; i++) {
                    if(userInput_letterflag[i] == 1){
                        continue;
                    }
                    for (int j = 0; j < 4; j++) {
                        if(user_Input_Word.charAt(i) == player1Word.charAt(j) && cpuWord_letterflag[j] == 0){
                            switch (i) {
                                case 0: a1_l1_p1.setBackground(Color.ORANGE);
                                break;
                                case 1: a1_l2_p1.setBackground(Color.ORANGE);
                                break;
                                case 2: a1_l3_p1.setBackground(Color.ORANGE);
                                break;
                                case 3: a1_l4_p1.setBackground(Color.ORANGE);
                                break;
                            }
                            cpuWord_letterflag[j] = 1;
                            break;
                        }
                    }
                }
                player1_Attempts--;

                break;

                case 4:
                attempt_Number_p1.setText("Attempt Left - 3");

                a2_l1_p1.setText(Conv_user_Input_Word[0]);
                a2_l1_p1.setBackground(Color.gray);

                a2_l2_p1.setText(Conv_user_Input_Word[1]);
                a2_l2_p1.setBackground(Color.gray);

                a2_l3_p1.setText(Conv_user_Input_Word[2]);
                a2_l3_p1.setBackground(Color.gray);

                a2_l4_p1.setText(Conv_user_Input_Word[3]);
                a2_l4_p1.setBackground(Color.gray);

                for (int i = 0; i < 4; i++) {
                    if(user_Input_Word.charAt(i) == player1Word.charAt(i)){
                        switch (i) {
                            case 0: a2_l1_p1.setBackground(Color.GREEN);
                            break;
                            case 1: a2_l2_p1.setBackground(Color.GREEN);
                            break;
                            case 2: a2_l3_p1.setBackground(Color.GREEN);
                            break;
                            case 3: a2_l4_p1.setBackground(Color.GREEN);
                            break;
                        }
                        cpuWord_letterflag[i] = 1;
                        userInput_letterflag[i] = 1;
                    }
                }
                for (int i = 0; i < 4; i++) {
                    if(userInput_letterflag[i] == 1){
                        continue;
                    }
                    for (int j = 0; j < 4; j++) {
                        if(user_Input_Word.charAt(i) == player1Word.charAt(j) && cpuWord_letterflag[j] == 0){
                            switch (i) {
                                case 0: a2_l1_p1.setBackground(Color.ORANGE);
                                break;
                                case 1: a2_l2_p1.setBackground(Color.ORANGE);
                                break;
                                case 2: a2_l3_p1.setBackground(Color.ORANGE);
                                break;
                                case 3: a2_l4_p1.setBackground(Color.ORANGE);
                                break;
                            }
                            cpuWord_letterflag[j] = 1;
                            break;
                        }
                    }
                }
                player1_Attempts--;
                break;

                case 3:
                attempt_Number_p1.setText("Attempt Left - 2");

                a3_l1_p1.setText(Conv_user_Input_Word[0]);
                a3_l1_p1.setBackground(Color.gray);

                a3_l2_p1.setText(Conv_user_Input_Word[1]);
                a3_l2_p1.setBackground(Color.gray);

                a3_l3_p1.setText(Conv_user_Input_Word[2]);
                a3_l3_p1.setBackground(Color.gray);

                a3_l4_p1.setText(Conv_user_Input_Word[3]);
                a3_l4_p1.setBackground(Color.gray);

                for (int i = 0; i < 4; i++) {
                    if(user_Input_Word.charAt(i) == player1Word.charAt(i)){
                        switch (i) {
                            case 0: a3_l1_p1.setBackground(Color.GREEN);
                            break;
                            case 1: a3_l2_p1.setBackground(Color.GREEN);
                            break;
                            case 2: a3_l3_p1.setBackground(Color.GREEN);
                            break;
                            case 3: a3_l4_p1.setBackground(Color.GREEN);
                            break;
                        }
                        cpuWord_letterflag[i] = 1;
                        userInput_letterflag[i] = 1;
                    }
                }
                for (int i = 0; i < 4; i++) {
                    if(userInput_letterflag[i] == 1){
                        continue;
                    }
                    for (int j = 0; j < 4; j++) {
                        if(user_Input_Word.charAt(i) == player1Word.charAt(j) && cpuWord_letterflag[j] == 0){
                            switch (i) {
                                case 0: a3_l1_p1.setBackground(Color.ORANGE);
                                break;
                                case 1: a3_l2_p1.setBackground(Color.ORANGE);
                                break;
                                case 2: a3_l3_p1.setBackground(Color.ORANGE);
                                break;
                                case 3: a3_l4_p1.setBackground(Color.ORANGE);
                                break;
                            }
                            cpuWord_letterflag[j] = 1;
                            break;
                        }
                    }
                }
                player1_Attempts--;
                break;

                case 2:
                attempt_Number_p1.setText("Attempt Left - 1");

                a4_l1_p1.setText(Conv_user_Input_Word[0]);
                a4_l1_p1.setBackground(Color.gray);

                a4_l2_p1.setText(Conv_user_Input_Word[1]);
                a4_l2_p1.setBackground(Color.gray);

                a4_l3_p1.setText(Conv_user_Input_Word[2]);
                a4_l3_p1.setBackground(Color.gray);

                a4_l4_p1.setText(Conv_user_Input_Word[3]);
                a4_l4_p1.setBackground(Color.gray);

                for (int i = 0; i < 4; i++) {
                    if(user_Input_Word.charAt(i) == player1Word.charAt(i)){
                        switch (i) {
                            case 0: a4_l1_p1.setBackground(Color.GREEN);
                            break;
                            case 1: a4_l2_p1.setBackground(Color.GREEN);
                            break;
                            case 2: a4_l3_p1.setBackground(Color.GREEN);
                            break;
                            case 3: a4_l4_p1.setBackground(Color.GREEN);
                            break;
                        }
                        cpuWord_letterflag[i] = 1;
                        userInput_letterflag[i] = 1;
                    }
                }
                for (int i = 0; i < 4; i++) {
                    if(userInput_letterflag[i] == 1){
                        continue;
                    }
                    for (int j = 0; j < 4; j++) {
                        if(user_Input_Word.charAt(i) == player1Word.charAt(j) && cpuWord_letterflag[j] == 0){
                            switch (i) {
                                case 0: a4_l1_p1.setBackground(Color.ORANGE);
                                break;
                                case 1: a4_l2_p1.setBackground(Color.ORANGE);
                                break;
                                case 2: a4_l3_p1.setBackground(Color.ORANGE);
                                break;
                                case 3: a4_l4_p1.setBackground(Color   .ORANGE);
                                break;
                            }
                            cpuWord_letterflag[j] = 1;
                            break;
                        }
                    }
                }
                player1_Attempts--;
                break;

                case 1:
                attempt_Number_p1.setText("Attempt Left - 0");

                a5_l1_p1.setText(Conv_user_Input_Word[0]);
                a5_l1_p1.setBackground(Color.gray);

                a5_l2_p1.setText(Conv_user_Input_Word[1]);
                a5_l2_p1.setBackground(Color.gray);

                a5_l3_p1.setText(Conv_user_Input_Word[2]);
                a5_l3_p1.setBackground(Color.gray);

                a5_l4_p1.setText(Conv_user_Input_Word[3]);
                a5_l4_p1.setBackground(Color.gray);

                for (int i = 0; i < 4; i++) {
                    if(user_Input_Word.charAt(i) == player1Word.charAt(i)){
                        switch (i) {
                            case 0: a5_l1_p1.setBackground(Color.GREEN);
                            break;
                            case 1: a5_l2_p1.setBackground(Color.GREEN);
                            break;
                            case 2: a5_l3_p1.setBackground(Color.GREEN);
                            break;
                            case 3: a5_l4_p1.setBackground(Color.GREEN);
                            break;
                        }
                        cpuWord_letterflag[i] = 1;
                        userInput_letterflag[i] = 1;
                    }
                }
                for (int i = 0; i < 4; i++) {
                    if(userInput_letterflag[i] == 1){
                        continue;
                    }
                    for (int j = 0; j < 4; j++) {
                        if(user_Input_Word.charAt(i) == player1Word.charAt(j) && cpuWord_letterflag[j] == 0){
                            switch (i) {
                                case 0: a5_l1_p1.setBackground(Color.ORANGE);
                                break;
                                case 1: a5_l2_p1.setBackground(Color.ORANGE);
                                break;
                                case 2: a5_l3_p1.setBackground(Color.ORANGE);
                                break;
                                case 3: a5_l4_p1.setBackground(Color.ORANGE);
                                break;
                            }
                            cpuWord_letterflag[j] = 1;
                            break;
                        }
                    }
                }
                player1_Attempts--;
                User_input_confirm_P1.setText("Finish");
                break;

                default:
                u_Score_player_1= 0;
                player1_Finished = true;
                User_input_p1.setEnabled(false);
                User_input_confirm_P1.setEnabled(false);
                User_input_confirm_P1.setText("P1 FAILED");
                JOptionPane.showMessageDialog(this, "Player 1 is Not Correct! Waiting for Player 2");
                break;
            }
            if(user_Input_Word.equalsIgnoreCase(player1Word)){
                u_Score_player_1 = ((player1_Attempts+1)*100);
                player1_Finished = true;    
                User_input_p1.setEnabled(false);
                User_input_confirm_P1.setEnabled(false);
                User_input_confirm_P1.setText("P1 DONE");
                JOptionPane.showMessageDialog(this, "Player 1 is Correct! Waiting for Player 2");   
            }
            checkGameEnd();
        }

    }//GEN-LAST:event_User_input_confirm_P1ActionPerformed

    
    
    
    
    
    private void User_input_p1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_User_input_p1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_User_input_p1ActionPerformed

    private void User_input_p2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_User_input_p2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_User_input_p2ActionPerformed

    
    
    private void User_input_confirm_P2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_User_input_confirm_P2ActionPerformed
        if(player2_Finished){
            return;
        }
        
        String user_Input_Word  = "";
        user_Input_Word = User_input_p2.getText().toLowerCase();

        String []Conv_user_Input_Word = user_Input_Word.split("");

        if(user_Input_Word.length() != 4){
            JOptionPane.showMessageDialog(null,"The word should be made of 4 Letters");
        } else {
            int []cpuWord_letterflag = {0,0,0,0};
            int []userInput_letterflag = {0,0,0,0};
            switch (player2_Attempts) {
                case 5:
                attempt_Number_p2.setText("Attempt Left - 4");
                a1_l1_p2.setText(Conv_user_Input_Word[0]);
                a1_l1_p2.setBackground(Color.gray);

                a1_l2_p2.setText(Conv_user_Input_Word[1]);
                a1_l2_p2.setBackground(Color.gray);

                a1_l3_p2.setText(Conv_user_Input_Word[2]);
                a1_l3_p2.setBackground(Color.gray);

                a1_l4_p2.setText(Conv_user_Input_Word[3]);
                a1_l4_p2.setBackground(Color.gray);

                for (int i = 0; i < 4; i++) {
                    if(user_Input_Word.charAt(i) == player2Word.charAt(i)){
                        switch (i) {
                            case 0: a1_l1_p2.setBackground(Color.GREEN);
                            break;
                            case 1: a1_l2_p2.setBackground(Color.GREEN);
                            break;
                            case 2: a1_l3_p2.setBackground(Color.GREEN);
                            break;
                            case 3: a1_l4_p2.setBackground(Color.GREEN);
                            break;
                        }
                        cpuWord_letterflag[i] = 1;
                        userInput_letterflag[i] = 1;
                    }
                }

                for (int i = 0; i < 4; i++) {
                    if(userInput_letterflag[i] == 1){
                        continue;
                    }
                    for (int j = 0; j < 4; j++) {
                        if(user_Input_Word.charAt(i) == player2Word.charAt(j) && cpuWord_letterflag[j] == 0){
                            switch (i) {
                                case 0: a1_l1_p2.setBackground(Color.ORANGE);
                                break;
                                case 1: a1_l2_p2.setBackground(Color.ORANGE);
                                break;
                                case 2: a1_l3_p2.setBackground(Color.ORANGE);
                                break;
                                case 3: a1_l4_p2.setBackground(Color.ORANGE);
                                break;
                            }
                            cpuWord_letterflag[j] = 1;
                            break;
                        }
                    }
                }
                player2_Attempts--;

                break;

                case 4:
                attempt_Number_p2.setText("Attempt Left - 3");

                a2_l1_p2.setText(Conv_user_Input_Word[0]);
                a2_l1_p2.setBackground(Color.gray);

                a2_l2_p2.setText(Conv_user_Input_Word[1]);
                a2_l2_p2.setBackground(Color.gray);

                a2_l3_p2.setText(Conv_user_Input_Word[2]);
                a2_l3_p2.setBackground(Color.gray);

                a2_l4_p2.setText(Conv_user_Input_Word[3]);
                a2_l4_p2.setBackground(Color.gray);

                for (int i = 0; i < 4; i++) {
                    if(user_Input_Word.charAt(i) == player2Word.charAt(i)){
                        switch (i) {
                            case 0: a2_l1_p2.setBackground(Color.GREEN);
                            break;
                            case 1: a2_l2_p2.setBackground(Color.GREEN);
                            break;
                            case 2: a2_l3_p2.setBackground(Color.GREEN);
                            break;
                            case 3: a2_l4_p2.setBackground(Color.GREEN);
                            break;
                        }
                        cpuWord_letterflag[i] = 1;
                        userInput_letterflag[i] = 1;
                    }
                }
                for (int i = 0; i < 4; i++) {
                    if(userInput_letterflag[i] == 1){
                        continue;
                    }
                    for (int j = 0; j < 4; j++) {
                        if(user_Input_Word.charAt(i) == player2Word.charAt(j) && cpuWord_letterflag[j] == 0){
                            switch (i) {
                                case 0: a2_l1_p2.setBackground(Color.ORANGE);
                                break;
                                case 1: a2_l2_p2.setBackground(Color.ORANGE);
                                break;
                                case 2: a2_l3_p2.setBackground(Color.ORANGE);
                                break;
                                case 3: a2_l4_p2.setBackground(Color.ORANGE);
                                break;
                            }
                            cpuWord_letterflag[j] = 1;
                            break;
                        }
                    }
                }
                player2_Attempts--;
                break;

                case 3:
                attempt_Number_p2.setText("Attempt Left - 2");

                a3_l1_p2.setText(Conv_user_Input_Word[0]);
                a3_l1_p2.setBackground(Color.gray);

                a3_l2_p2.setText(Conv_user_Input_Word[1]);
                a3_l2_p2.setBackground(Color.gray);

                a3_l3_p2.setText(Conv_user_Input_Word[2]);
                a3_l3_p2.setBackground(Color.gray);

                a3_l4_p2.setText(Conv_user_Input_Word[3]);
                a3_l4_p2.setBackground(Color.gray);

                for (int i = 0; i < 4; i++) {
                    if(user_Input_Word.charAt(i) == player2Word.charAt(i)){
                        switch (i) {
                            case 0: a3_l1_p2.setBackground(Color.GREEN);
                            break;
                            case 1: a3_l2_p2.setBackground(Color.GREEN);
                            break;
                            case 2: a3_l3_p2.setBackground(Color.GREEN);
                            break;
                            case 3: a3_l4_p2.setBackground(Color.GREEN);
                            break;
                        }
                        cpuWord_letterflag[i] = 1;
                        userInput_letterflag[i] = 1;
                    }
                }
                for (int i = 0; i < 4; i++) {
                    if(userInput_letterflag[i] == 1){
                        continue;
                    }
                    for (int j = 0; j < 4; j++) {
                        if(user_Input_Word.charAt(i) == player2Word.charAt(j) && cpuWord_letterflag[j] == 0){
                            switch (i) {
                                case 0: a3_l1_p2.setBackground(Color.ORANGE);
                                break;
                                case 1: a3_l2_p2.setBackground(Color.ORANGE);
                                break;
                                case 2: a3_l3_p2.setBackground(Color.ORANGE);
                                break;
                                case 3: a3_l4_p2.setBackground(Color.ORANGE);
                                break;
                            }
                            cpuWord_letterflag[j] = 1;
                            break;
                        }
                    }
                }
                player2_Attempts--;
                break;

                case 2:
                attempt_Number_p2.setText("Attempt Left - 1");

                a4_l1_p2.setText(Conv_user_Input_Word[0]);
                a4_l1_p2.setBackground(Color.gray);

                a4_l2_p2.setText(Conv_user_Input_Word[1]);
                a4_l2_p2.setBackground(Color.gray);

                a4_l3_p2.setText(Conv_user_Input_Word[2]);
                a4_l3_p2.setBackground(Color.gray);

                a4_l4_p2.setText(Conv_user_Input_Word[3]);
                a4_l4_p2.setBackground(Color.gray);

                for (int i = 0; i < 4; i++) {
                    if(user_Input_Word.charAt(i) == player2Word.charAt(i)){
                        switch (i) {
                            case 0: a4_l1_p2.setBackground(Color.GREEN);
                            break;
                            case 1: a4_l2_p2.setBackground(Color.GREEN);
                            break;
                            case 2: a4_l3_p2.setBackground(Color.GREEN);
                            break;
                            case 3: a4_l4_p2.setBackground(Color.GREEN);
                            break;
                        }
                        cpuWord_letterflag[i] = 1;
                        userInput_letterflag[i] = 1;
                    }
                }
                for (int i = 0; i < 4; i++) {
                    if(userInput_letterflag[i] == 1){
                        continue;
                    }
                    for (int j = 0; j < 4; j++) {
                        if(user_Input_Word.charAt(i) == player2Word.charAt(j) && cpuWord_letterflag[j] == 0){
                            switch (i) {
                                case 0: a4_l1_p2.setBackground(Color.ORANGE);
                                break;
                                case 1: a4_l2_p2.setBackground(Color.ORANGE);
                                break;
                                case 2: a4_l3_p2.setBackground(Color.ORANGE);
                                break;
                                case 3: a4_l4_p2.setBackground(Color   .ORANGE);
                                break;
                            }
                            cpuWord_letterflag[j] = 1;
                            break;
                        }
                    }
                }
                player2_Attempts--;
                break;

                case 1:
                attempt_Number_p2.setText("Attempt Left - 0");

                a5_l1_p2.setText(Conv_user_Input_Word[0]);
                a5_l1_p2.setBackground(Color.gray);

                a5_l2_p2.setText(Conv_user_Input_Word[1]);
                a5_l2_p2.setBackground(Color.gray);

                a5_l3_p2.setText(Conv_user_Input_Word[2]);
                a5_l3_p2.setBackground(Color.gray);

                a5_l4_p2.setText(Conv_user_Input_Word[3]);
                a5_l4_p2.setBackground(Color.gray);

                for (int i = 0; i < 4; i++) {
                    if(user_Input_Word.charAt(i) == player2Word.charAt(i)){
                        switch (i) {
                            case 0: a5_l1_p2.setBackground(Color.GREEN);
                            break;
                            case 1: a5_l2_p2.setBackground(Color.GREEN);
                            break;
                            case 2: a5_l3_p2.setBackground(Color.GREEN);
                            break;
                            case 3: a5_l4_p2.setBackground(Color.GREEN);
                            break;
                        }
                        cpuWord_letterflag[i] = 1;
                        userInput_letterflag[i] = 1;
                    }
                }
                for (int i = 0; i < 4; i++) {
                    if(userInput_letterflag[i] == 1){
                        continue;
                    }
                    for (int j = 0; j < 4; j++) {
                        if(user_Input_Word.charAt(i) == player2Word.charAt(j) && cpuWord_letterflag[j] == 0){
                            switch (i) {
                                case 0: a5_l1_p2.setBackground(Color.ORANGE);
                                break;
                                case 1: a5_l2_p2.setBackground(Color.ORANGE);
                                break;
                                case 2: a5_l3_p2.setBackground(Color.ORANGE);
                                break;
                                case 3: a5_l4_p2.setBackground(Color.ORANGE);
                                break;
                            }
                            cpuWord_letterflag[j] = 1;
                            break;
                        }
                    }
                }
                player2_Attempts--;
                User_input_confirm_P2.setText("Finish");
                break;

                default:
                u_Score_player_2= 0;

                player1_Finished = true;
                User_input_p1.setEnabled(false);
                User_input_confirm_P2.setEnabled(false);
                User_input_confirm_P2.setText("P2 FAILED");
                JOptionPane.showMessageDialog(this, "Player 2 is Not Correct! Waiting for Player 1");
                break;
            }
            if(user_Input_Word.equalsIgnoreCase(player2Word)){
                u_Score_player_2 = ((player2_Attempts+1)*100);
                player2_Finished = true;    
                User_input_p1.setEnabled(false);
                User_input_confirm_P2.setEnabled(false);
                User_input_confirm_P2.setText("P2 DONE");
                JOptionPane.showMessageDialog(this, "Player 2 is Correct! Waiting for Player 1");
            }
        checkGameEnd();
        }
    }//GEN-LAST:event_User_input_confirm_P2ActionPerformed

    private void checkGameEnd() {
        // Only run logic if BOTH players have finished their games
        if (player1_Finished && player2_Finished) {
            String message = "";
            if (u_Score_player_1 > u_Score_player_2) {
                message = "Player 1 Wins!\nP1 Score: " + u_Score_player_1 + "\nP2 Score: " + u_Score_player_2;
            } else if (u_Score_player_2 > u_Score_player_1) {
                message = "Player 2 Wins!\nP2 Score: " + u_Score_player_2 + "\nP1 Score: " + u_Score_player_1;
            } else {
                message = "It's a Draw!\nScore: " + u_Score_player_1;
            }
            
            // Show result and go to win screen
            JOptionPane.showMessageDialog(this, message);
            dispose();
            MainGame_Menu back = new MainGame_Menu();
            back.setVisible(true);
            
        }
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws FileNotFoundException{
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainGame_Versus().setVisible(true));
        
                
        
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton User_input_confirm_P1;
    private javax.swing.JButton User_input_confirm_P2;
    private javax.swing.JTextField User_input_p1;
    private javax.swing.JTextField User_input_p2;
    private javax.swing.JLabel a1_l1_p1;
    private javax.swing.JLabel a1_l1_p2;
    private javax.swing.JLabel a1_l2_p1;
    private javax.swing.JLabel a1_l2_p2;
    private javax.swing.JLabel a1_l3_p1;
    private javax.swing.JLabel a1_l3_p2;
    private javax.swing.JLabel a1_l4_p1;
    private javax.swing.JLabel a1_l4_p2;
    private javax.swing.JLabel a2_l1_p1;
    private javax.swing.JLabel a2_l1_p2;
    private javax.swing.JLabel a2_l2_p1;
    private javax.swing.JLabel a2_l2_p2;
    private javax.swing.JLabel a2_l3_p1;
    private javax.swing.JLabel a2_l3_p2;
    private javax.swing.JLabel a2_l4_p1;
    private javax.swing.JLabel a2_l4_p2;
    private javax.swing.JLabel a3_l1_p1;
    private javax.swing.JLabel a3_l1_p2;
    private javax.swing.JLabel a3_l2_p1;
    private javax.swing.JLabel a3_l2_p2;
    private javax.swing.JLabel a3_l3_p1;
    private javax.swing.JLabel a3_l3_p2;
    private javax.swing.JLabel a3_l4_p1;
    private javax.swing.JLabel a3_l4_p2;
    private javax.swing.JLabel a4_l1_p1;
    private javax.swing.JLabel a4_l1_p2;
    private javax.swing.JLabel a4_l2_p1;
    private javax.swing.JLabel a4_l2_p2;
    private javax.swing.JLabel a4_l3_p1;
    private javax.swing.JLabel a4_l3_p2;
    private javax.swing.JLabel a4_l4_p1;
    private javax.swing.JLabel a4_l4_p2;
    private javax.swing.JLabel a5_l1_p1;
    private javax.swing.JLabel a5_l1_p2;
    private javax.swing.JLabel a5_l2_p1;
    private javax.swing.JLabel a5_l2_p2;
    private javax.swing.JLabel a5_l3_p1;
    private javax.swing.JLabel a5_l3_p2;
    private javax.swing.JLabel a5_l4_p1;
    private javax.swing.JLabel a5_l4_p2;
    private javax.swing.JLabel attempt_Number_p1;
    private javax.swing.JLabel attempt_Number_p2;
    private javax.swing.JLabel back_Button;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel title_Game;
    // End of variables declaration//GEN-END:variables
}
