/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.two.player.wordle;

import java.io.FileNotFoundException;
import javax.swing.JOptionPane;


/**
 *
 * @author Joshua
 */
public class MainGame_Leaderboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainGame_Leaderboard.class.getName());

      
    
    /**
     * Creates new form MainGame_Tutorial
     */
    public MainGame_Leaderboard() {
        initComponents();
        
        scoreLogic loadScore = new scoreLogic();
        H_Score.setText(String.valueOf(loadScore.bestStreakScore));
        H_Streak.setText(String.valueOf(loadScore.longestStreakCount));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        title_Game1 = new javax.swing.JLabel();
        play_Button = new javax.swing.JButton();
        back_Button = new javax.swing.JLabel();
        H_Score = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        score_Label = new javax.swing.JLabel();
        streak_Label = new javax.swing.JLabel();
        H_Streak = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 600));

        jPanel1.setBackground(new java.awt.Color(119, 136, 115));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 600));

        title_Game1.setFont(new java.awt.Font("Modern No. 20", 0, 36)); // NOI18N
        title_Game1.setForeground(new java.awt.Color(210, 220, 182));
        title_Game1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title_Game1.setText("WORDLE");

        play_Button.setBackground(new java.awt.Color(210, 220, 182));
        play_Button.setForeground(new java.awt.Color(119, 136, 115));
        play_Button.setText("PLAY");
        play_Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        play_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                play_ButtonActionPerformed(evt);
            }
        });

        back_Button.setForeground(new java.awt.Color(210, 220, 182));
        back_Button.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        back_Button.setText("Back");
        back_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back_ButtonMouseClicked(evt);
            }
        });

        H_Score.setBackground(new java.awt.Color(119, 136, 115));
        H_Score.setFont(new java.awt.Font("AirbusDisp2", 1, 24)); // NOI18N
        H_Score.setForeground(new java.awt.Color(210, 220, 182));
        H_Score.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        H_Score.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setBackground(new java.awt.Color(119, 136, 115));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(210, 220, 182));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("\"No One is above\"");

        score_Label.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        score_Label.setForeground(new java.awt.Color(210, 220, 182));
        score_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        score_Label.setText("HIGH SCORE TO BEAT:");

        streak_Label.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        streak_Label.setForeground(new java.awt.Color(210, 220, 182));
        streak_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        streak_Label.setText("LONGEST STREAK:");

        H_Streak.setBackground(new java.awt.Color(119, 136, 115));
        H_Streak.setFont(new java.awt.Font("AirbusDisp2", 1, 24)); // NOI18N
        H_Streak.setForeground(new java.awt.Color(210, 220, 182));
        H_Streak.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        H_Streak.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(title_Game1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(H_Streak, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(H_Score, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(back_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(play_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(144, 144, 144))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(streak_Label)
                        .addGap(102, 102, 102))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(155, 155, 155))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(91, Short.MAX_VALUE)
                    .addComponent(score_Label)
                    .addGap(70, 70, 70)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(title_Game1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(H_Score, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(streak_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(H_Streak, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(play_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(back_Button)
                .addGap(71, 71, 71))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(92, 92, 92)
                    .addComponent(score_Label)
                    .addContainerGap(476, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void back_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_ButtonMouseClicked
        dispose();
        MainGame_Menu btn_back = new MainGame_Menu();
        btn_back.setVisible(true);
    }//GEN-LAST:event_back_ButtonMouseClicked

    private void play_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_play_ButtonActionPerformed
        dispose();
        MainGame_ModeSelect btn_ModeSelect = new MainGame_ModeSelect();
        btn_ModeSelect.setVisible(true);           
    }//GEN-LAST:event_play_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainGame_Leaderboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel H_Score;
    private javax.swing.JLabel H_Streak;
    private javax.swing.JLabel back_Button;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton play_Button;
    private javax.swing.JLabel score_Label;
    private javax.swing.JLabel streak_Label;
    private javax.swing.JLabel title_Game1;
    // End of variables declaration//GEN-END:variables
}
