/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.two.player.wordle;

import java.awt.Color;
import javax.swing.JOptionPane;
import java.util.Scanner;
import java.util.Random;
import java.io.File;
import java.io.FileNotFoundException;

/**
 *
 * @author Joshua
 */
public class MainGame_Interface extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainGame_Interface.class.getName());

    /**
     * Creates new form MainGame_Interface
     */
    private int u_Attempts = 5; // IF ADDING MOR ATTEMPTS DO NOT FORGET TO CHNAGE THIS 
    private String cpuWord = ""; // global variable for the cpu word 
    private int u_Score = 0;
    
    
    
    public MainGame_Interface() {
        initComponents();
        
        // This will pre load the word as the app opens 
        // I have a text document words.txt that has 100 4 letter word 
        /* i have a randome number generator and based from that number 
        i will traverse through the text file and it will pick a random word 
        based from the random numebrg enerator */
        try {
            File fopen = new File("C:/Users/Joshua/Documents/NetBeansProjects/TWO-PLAYER-WORDLE/src/main/java/com/mycompany/two/player/wordle/words.txt");
            Scanner cpuScanner = new Scanner(fopen);        
        
            //random number generator for the word 
            Random word_Generator = new Random(); // This is the consturctor for the number generator 
            int max = 100; // RELIES ON THE NUMBER OF WORDS ON THE WORDS.TXT -- REMEMBER TO CHANGE THE VALUE OF THIS !!!!
            int word_Generator_Index = word_Generator.nextInt(max); // Random number generator range - From 0 to 100

            // loop for traversing 
            while(cpuScanner.hasNextLine()){
                for (int i = 0; i < word_Generator_Index-1; i++) {
                    cpuScanner.nextLine();
                }
                cpuWord = cpuScanner.nextLine();
                break;
            }
            
            // Any code here will run before the clicks 
            attempt_Number.setText("Attempt Left - 5");
            
            JOptionPane.showMessageDialog(null, cpuWord);


            cpuScanner.close();
        } catch (Exception FileNotException) {
            JOptionPane.showMessageDialog(null, "There was a problem in loading the Word Database");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frame_afterGame = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        c1_text = new javax.swing.JLabel();
        c3_text_Score = new javax.swing.JLabel();
        c2_text = new javax.swing.JLabel();
        backbtn = new javax.swing.JButton();
        nwgamebtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        User_input = new javax.swing.JTextField();
        User_input_confirm = new javax.swing.JButton();
        a1_l4 = new javax.swing.JLabel();
        a1_l1 = new javax.swing.JLabel();
        a1_l2 = new javax.swing.JLabel();
        a1_l3 = new javax.swing.JLabel();
        a2_l1 = new javax.swing.JLabel();
        a2_l2 = new javax.swing.JLabel();
        a2_l3 = new javax.swing.JLabel();
        a2_l4 = new javax.swing.JLabel();
        a3_l1 = new javax.swing.JLabel();
        a3_l2 = new javax.swing.JLabel();
        a3_l3 = new javax.swing.JLabel();
        a3_l4 = new javax.swing.JLabel();
        a4_l1 = new javax.swing.JLabel();
        a4_l2 = new javax.swing.JLabel();
        a4_l3 = new javax.swing.JLabel();
        a4_l4 = new javax.swing.JLabel();
        title_Game = new javax.swing.JLabel();
        attempt_Number = new javax.swing.JLabel();
        back_Button = new javax.swing.JLabel();
        a5_l1 = new javax.swing.JLabel();
        a5_l2 = new javax.swing.JLabel();
        a5_l3 = new javax.swing.JLabel();
        a5_l4 = new javax.swing.JLabel();

        frame_afterGame.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        frame_afterGame.setAlwaysOnTop(true);
        frame_afterGame.setMaximumSize(new java.awt.Dimension(400, 300));
        frame_afterGame.setMinimumSize(new java.awt.Dimension(400, 300));
        frame_afterGame.setPreferredSize(new java.awt.Dimension(400, 400));
        frame_afterGame.setResizable(false);

        jPanel2.setMaximumSize(new java.awt.Dimension(400, 400));
        jPanel2.setMinimumSize(new java.awt.Dimension(400, 400));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 400));

        c1_text.setFont(new java.awt.Font("AirbusDisp2", 1, 14)); // NOI18N
        c1_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        c1_text.setText("Congratulations");

        c3_text_Score.setFont(new java.awt.Font("AirbusDisp2", 1, 14)); // NOI18N
        c3_text_Score.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        c2_text.setFont(new java.awt.Font("AirbusDisp2", 1, 14)); // NOI18N
        c2_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        c2_text.setText("you guessed the right word");

        backbtn.setText("Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        nwgamebtn.setText("New Game");
        nwgamebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nwgamebtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(nwgamebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(c3_text_Score, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(c2_text, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(c1_text, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(61, 61, 61))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(c1_text, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c2_text, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c3_text_Score, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nwgamebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout frame_afterGameLayout = new javax.swing.GroupLayout(frame_afterGame.getContentPane());
        frame_afterGame.getContentPane().setLayout(frame_afterGameLayout);
        frame_afterGameLayout.setHorizontalGroup(
            frame_afterGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        frame_afterGameLayout.setVerticalGroup(
            frame_afterGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(240, 234, 214));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(240, 234, 214));
        setSize(new java.awt.Dimension(400, 600));

        jPanel1.setBackground(new java.awt.Color(119, 136, 115));
        jPanel1.setForeground(new java.awt.Color(119, 136, 115));
        jPanel1.setToolTipText("");
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 600));

        User_input.setBackground(new java.awt.Color(241, 243, 224));
        User_input.setFont(new java.awt.Font("AirbusDisp2", 1, 12)); // NOI18N
        User_input.setForeground(new java.awt.Color(119, 136, 115));
        User_input.setText("ENTER A 4 LETTER WORD");
        User_input.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        User_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                User_inputActionPerformed(evt);
            }
        });

        User_input_confirm.setBackground(new java.awt.Color(210, 220, 182));
        User_input_confirm.setFont(new java.awt.Font("AirbusDisp2", 1, 14)); // NOI18N
        User_input_confirm.setForeground(new java.awt.Color(119, 136, 115));
        User_input_confirm.setText("Confirm");
        User_input_confirm.setAlignmentY(0.0F);
        User_input_confirm.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        User_input_confirm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        User_input_confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                User_input_confirmActionPerformed(evt);
            }
        });

        a1_l4.setBackground(new java.awt.Color(161, 188, 152));
        a1_l4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a1_l4.setForeground(new java.awt.Color(241, 243, 224));
        a1_l4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a1_l4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a1_l4.setOpaque(true);

        a1_l1.setBackground(new java.awt.Color(161, 188, 152));
        a1_l1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a1_l1.setForeground(new java.awt.Color(241, 243, 224));
        a1_l1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a1_l1.setToolTipText("");
        a1_l1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a1_l1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        a1_l1.setInheritsPopupMenu(false);
        a1_l1.setOpaque(true);

        a1_l2.setBackground(new java.awt.Color(161, 188, 152));
        a1_l2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a1_l2.setForeground(new java.awt.Color(241, 243, 224));
        a1_l2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a1_l2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a1_l2.setOpaque(true);

        a1_l3.setBackground(new java.awt.Color(161, 188, 152));
        a1_l3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a1_l3.setForeground(new java.awt.Color(241, 243, 224));
        a1_l3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a1_l3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a1_l3.setOpaque(true);

        a2_l1.setBackground(new java.awt.Color(161, 188, 152));
        a2_l1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a2_l1.setForeground(new java.awt.Color(241, 243, 224));
        a2_l1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a2_l1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a2_l1.setOpaque(true);

        a2_l2.setBackground(new java.awt.Color(161, 188, 152));
        a2_l2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a2_l2.setForeground(new java.awt.Color(241, 243, 224));
        a2_l2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a2_l2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a2_l2.setOpaque(true);

        a2_l3.setBackground(new java.awt.Color(161, 188, 152));
        a2_l3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a2_l3.setForeground(new java.awt.Color(241, 243, 224));
        a2_l3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a2_l3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a2_l3.setOpaque(true);

        a2_l4.setBackground(new java.awt.Color(161, 188, 152));
        a2_l4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a2_l4.setForeground(new java.awt.Color(241, 243, 224));
        a2_l4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a2_l4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a2_l4.setOpaque(true);

        a3_l1.setBackground(new java.awt.Color(161, 188, 152));
        a3_l1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a3_l1.setForeground(new java.awt.Color(241, 243, 224));
        a3_l1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a3_l1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a3_l1.setOpaque(true);

        a3_l2.setBackground(new java.awt.Color(161, 188, 152));
        a3_l2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a3_l2.setForeground(new java.awt.Color(241, 243, 224));
        a3_l2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a3_l2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a3_l2.setOpaque(true);

        a3_l3.setBackground(new java.awt.Color(161, 188, 152));
        a3_l3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a3_l3.setForeground(new java.awt.Color(241, 243, 224));
        a3_l3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a3_l3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a3_l3.setOpaque(true);

        a3_l4.setBackground(new java.awt.Color(161, 188, 152));
        a3_l4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a3_l4.setForeground(new java.awt.Color(241, 243, 224));
        a3_l4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a3_l4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a3_l4.setOpaque(true);

        a4_l1.setBackground(new java.awt.Color(161, 188, 152));
        a4_l1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a4_l1.setForeground(new java.awt.Color(241, 243, 224));
        a4_l1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a4_l1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a4_l1.setOpaque(true);

        a4_l2.setBackground(new java.awt.Color(161, 188, 152));
        a4_l2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a4_l2.setForeground(new java.awt.Color(241, 243, 224));
        a4_l2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a4_l2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a4_l2.setOpaque(true);

        a4_l3.setBackground(new java.awt.Color(161, 188, 152));
        a4_l3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a4_l3.setForeground(new java.awt.Color(241, 243, 224));
        a4_l3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a4_l3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a4_l3.setOpaque(true);

        a4_l4.setBackground(new java.awt.Color(161, 188, 152));
        a4_l4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a4_l4.setForeground(new java.awt.Color(241, 243, 224));
        a4_l4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a4_l4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a4_l4.setOpaque(true);

        title_Game.setBackground(new java.awt.Color(49, 54, 71));
        title_Game.setFont(new java.awt.Font("Modern No. 20", 0, 36)); // NOI18N
        title_Game.setForeground(new java.awt.Color(210, 220, 182));
        title_Game.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title_Game.setText("WORDLE");

        attempt_Number.setFont(new java.awt.Font("AirbusDisp2", 0, 14)); // NOI18N
        attempt_Number.setForeground(new java.awt.Color(210, 220, 182));
        attempt_Number.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        back_Button.setFont(new java.awt.Font("AirbusDisp2", 0, 12)); // NOI18N
        back_Button.setForeground(new java.awt.Color(210, 220, 182));
        back_Button.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        back_Button.setText("Back");
        back_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back_ButtonMouseClicked(evt);
            }
        });

        a5_l1.setBackground(new java.awt.Color(161, 188, 152));
        a5_l1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a5_l1.setForeground(new java.awt.Color(241, 243, 224));
        a5_l1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a5_l1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a5_l1.setOpaque(true);

        a5_l2.setBackground(new java.awt.Color(161, 188, 152));
        a5_l2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a5_l2.setForeground(new java.awt.Color(241, 243, 224));
        a5_l2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a5_l2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a5_l2.setOpaque(true);

        a5_l3.setBackground(new java.awt.Color(161, 188, 152));
        a5_l3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a5_l3.setForeground(new java.awt.Color(241, 243, 224));
        a5_l3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a5_l3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a5_l3.setOpaque(true);

        a5_l4.setBackground(new java.awt.Color(161, 188, 152));
        a5_l4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a5_l4.setForeground(new java.awt.Color(241, 243, 224));
        a5_l4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a5_l4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a5_l4.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(User_input_confirm, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(title_Game, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(back_Button))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(attempt_Number, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(a3_l1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(a3_l2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(a3_l3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(a3_l4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(a2_l1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(a2_l2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(a2_l3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(a2_l4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(a1_l1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(a1_l2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(a1_l3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(a1_l4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(a4_l1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(a4_l2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(a4_l3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(a4_l4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(a5_l1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(a5_l2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(a5_l3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(a5_l4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(User_input, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(title_Game, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(a1_l1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a1_l2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(a1_l4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(a1_l3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(a2_l1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a2_l2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(a2_l4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(a2_l3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(a3_l1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a3_l2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(a3_l4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(a3_l3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(a4_l1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a4_l2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(a4_l4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(a4_l3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(a5_l1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a5_l2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(a5_l4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(a5_l3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(User_input, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(attempt_Number, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(User_input_confirm, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(back_Button)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    
    
    // back button
    private void back_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_ButtonMouseClicked
        MainGame_Menu btn_back = new MainGame_Menu();
        if(u_Attempts != 0){
            int dialog_Result = JOptionPane.showConfirmDialog(null, "All porgress will be lost if you go back", "Go Back?", JOptionPane.YES_NO_OPTION);
            if(dialog_Result == JOptionPane.YES_OPTION){
                dispose();
                btn_back.setVisible(true);
            } else if(dialog_Result == JOptionPane.NO_OPTION){
                //do nothing
            }
        } else if (u_Attempts == 0){
            dispose();
            btn_back.setVisible(true);

        }

    }//GEN-LAST:event_back_ButtonMouseClicked

    private void User_input_confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_User_input_confirmActionPerformed
        String user_Input_Word  = "";
        user_Input_Word = User_input.getText().toLowerCase();

        String []Conv_user_Input_Word = user_Input_Word.split("");

        if(user_Input_Word.length() != 4){
            JOptionPane.showMessageDialog(null,"The word should be made of 4 Letters");
        } else {
            int []cpuWord_letterflag = {0,0,0,0};
            int []userInput_letterflag = {0,0,0,0};
            switch (u_Attempts) {
                case 5:
                attempt_Number.setText("Attempt Left - 4");
                a1_l1.setText(Conv_user_Input_Word[0]);
                a1_l1.setBackground(Color.gray);

                a1_l2.setText(Conv_user_Input_Word[1]);
                a1_l2.setBackground(Color.gray);

                a1_l3.setText(Conv_user_Input_Word[2]);
                a1_l3.setBackground(Color.gray);

                a1_l4.setText(Conv_user_Input_Word[3]);
                a1_l4.setBackground(Color.gray);

                for (int i = 0; i < 4; i++) {
                    if(user_Input_Word.charAt(i) == cpuWord.charAt(i)){
                        switch (i) {
                            case 0: a1_l1.setBackground(Color.GREEN);
                            break;
                            case 1: a1_l2.setBackground(Color.GREEN);
                            break;
                            case 2: a1_l3.setBackground(Color.GREEN);
                            break;
                            case 3: a1_l4.setBackground(Color.GREEN);
                            break;
                        }
                        cpuWord_letterflag[i] = 1;
                        userInput_letterflag[i] = 1;
                    }
                }

                for (int i = 0; i < 4; i++) {
                    if(userInput_letterflag[i] == 1){
                        continue;
                    }
                    for (int j = 0; j < 4; j++) {
                        if(user_Input_Word.charAt(i) == cpuWord.charAt(j) && cpuWord_letterflag[j] == 0){
                            switch (i) {
                                case 0: a1_l1.setBackground(Color.ORANGE);
                                break;
                                case 1: a1_l2.setBackground(Color.ORANGE);
                                break;
                                case 2: a1_l3.setBackground(Color.ORANGE);
                                break;
                                case 3: a1_l4.setBackground(Color.ORANGE);
                                break;
                            }
                            cpuWord_letterflag[j] = 1;
                            break;
                        }
                    }
                }
                u_Attempts--;

                break;

                case 4:
                attempt_Number.setText("Attempt Left - 3");

                a2_l1.setText(Conv_user_Input_Word[0]);
                a2_l1.setBackground(Color.gray);

                a2_l2.setText(Conv_user_Input_Word[1]);
                a2_l2.setBackground(Color.gray);

                a2_l3.setText(Conv_user_Input_Word[2]);
                a2_l3.setBackground(Color.gray);

                a2_l4.setText(Conv_user_Input_Word[3]);
                a2_l4.setBackground(Color.gray);

                for (int i = 0; i < 4; i++) {
                    if(user_Input_Word.charAt(i) == cpuWord.charAt(i)){
                        switch (i) {
                            case 0: a2_l1.setBackground(Color.GREEN);
                            break;
                            case 1: a2_l2.setBackground(Color.GREEN);
                            break;
                            case 2: a2_l3.setBackground(Color.GREEN);
                            break;
                            case 3: a2_l4.setBackground(Color.GREEN);
                            break;
                        }
                        cpuWord_letterflag[i] = 1;
                        userInput_letterflag[i] = 1;
                    }
                }
                for (int i = 0; i < 4; i++) {
                    if(userInput_letterflag[i] == 1){
                        continue;
                    }
                    for (int j = 0; j < 4; j++) {
                        if(user_Input_Word.charAt(i) == cpuWord.charAt(j) && cpuWord_letterflag[j] == 0){
                            switch (i) {
                                case 0: a2_l1.setBackground(Color.ORANGE);
                                break;
                                case 1: a2_l2.setBackground(Color.ORANGE);
                                break;
                                case 2: a2_l3.setBackground(Color.ORANGE);
                                break;
                                case 3: a2_l4.setBackground(Color.ORANGE);
                                break;
                            }
                            cpuWord_letterflag[j] = 1;
                            break;
                        }
                    }
                }
                u_Attempts--;
                break;

                case 3:
                attempt_Number.setText("Attempt Left - 2");

                a3_l1.setText(Conv_user_Input_Word[0]);
                a3_l1.setBackground(Color.gray);

                a3_l2.setText(Conv_user_Input_Word[1]);
                a3_l2.setBackground(Color.gray);

                a3_l3.setText(Conv_user_Input_Word[2]);
                a3_l3.setBackground(Color.gray);

                a3_l4.setText(Conv_user_Input_Word[3]);
                a3_l4.setBackground(Color.gray);

                for (int i = 0; i < 4; i++) {
                    if(user_Input_Word.charAt(i) == cpuWord.charAt(i)){
                        switch (i) {
                            case 0: a3_l1.setBackground(Color.GREEN);
                            break;
                            case 1: a3_l2.setBackground(Color.GREEN);
                            break;
                            case 2: a3_l3.setBackground(Color.GREEN);
                            break;
                            case 3: a3_l4.setBackground(Color.GREEN);
                            break;
                        }
                        cpuWord_letterflag[i] = 1;
                        userInput_letterflag[i] = 1;
                    }
                }
                for (int i = 0; i < 4; i++) {
                    if(userInput_letterflag[i] == 1){
                        continue;
                    }
                    for (int j = 0; j < 4; j++) {
                        if(user_Input_Word.charAt(i) == cpuWord.charAt(j) && cpuWord_letterflag[j] == 0){
                            switch (i) {
                                case 0: a3_l1.setBackground(Color.ORANGE);
                                break;
                                case 1: a3_l2.setBackground(Color.ORANGE);
                                break;
                                case 2: a3_l3.setBackground(Color.ORANGE);
                                break;
                                case 3: a3_l4.setBackground(Color.ORANGE);
                                break;
                            }
                            cpuWord_letterflag[j] = 1;
                            break;
                        }
                    }
                }
                u_Attempts--;
                break;

                case 2:
                attempt_Number.setText("Attempt Left - 1");

                a4_l1.setText(Conv_user_Input_Word[0]);
                a4_l1.setBackground(Color.gray);

                a4_l2.setText(Conv_user_Input_Word[1]);
                a4_l2.setBackground(Color.gray);

                a4_l3.setText(Conv_user_Input_Word[2]);
                a4_l3.setBackground(Color.gray);

                a4_l4.setText(Conv_user_Input_Word[3]);
                a4_l4.setBackground(Color.gray);

                for (int i = 0; i < 4; i++) {
                    if(user_Input_Word.charAt(i) == cpuWord.charAt(i)){
                        switch (i) {
                            case 0: a4_l1.setBackground(Color.GREEN);
                            break;
                            case 1: a4_l2.setBackground(Color.GREEN);
                            break;
                            case 2: a4_l3.setBackground(Color.GREEN);
                            break;
                            case 3: a4_l4.setBackground(Color.GREEN);
                            break;
                        }
                        cpuWord_letterflag[i] = 1;
                        userInput_letterflag[i] = 1;
                    }
                }
                for (int i = 0; i < 4; i++) {
                    if(userInput_letterflag[i] == 1){
                        continue;
                    }
                    for (int j = 0; j < 4; j++) {
                        if(user_Input_Word.charAt(i) == cpuWord.charAt(j) && cpuWord_letterflag[j] == 0){
                            switch (i) {
                                case 0: a4_l1.setBackground(Color.ORANGE);
                                break;
                                case 1: a4_l2.setBackground(Color.ORANGE);
                                break;
                                case 2: a4_l3.setBackground(Color.ORANGE);
                                break;
                                case 3: a4_l4.setBackground(Color   .ORANGE);
                                break;
                            }
                            cpuWord_letterflag[j] = 1;
                            break;
                        }
                    }
                }
                u_Attempts--;
                break;

                case 1:
                attempt_Number.setText("Attempt Left - 0");

                a5_l1.setText(Conv_user_Input_Word[0]);
                a5_l1.setBackground(Color.gray);

                a5_l2.setText(Conv_user_Input_Word[1]);
                a5_l2.setBackground(Color.gray);

                a5_l3.setText(Conv_user_Input_Word[2]);
                a5_l3.setBackground(Color.gray);

                a5_l4.setText(Conv_user_Input_Word[3]);
                a5_l4.setBackground(Color.gray);

                for (int i = 0; i < 4; i++) {
                    if(user_Input_Word.charAt(i) == cpuWord.charAt(i)){
                        switch (i) {
                            case 0: a5_l1.setBackground(Color.GREEN);
                            break;
                            case 1: a5_l2.setBackground(Color.GREEN);
                            break;
                            case 2: a5_l3.setBackground(Color.GREEN);
                            break;
                            case 3: a5_l4.setBackground(Color.GREEN);
                            break;
                        }
                        cpuWord_letterflag[i] = 1;
                        userInput_letterflag[i] = 1;
                    }
                }
                for (int i = 0; i < 4; i++) {
                    if(userInput_letterflag[i] == 1){
                        continue;
                    }
                    for (int j = 0; j < 4; j++) {
                        if(user_Input_Word.charAt(i) == cpuWord.charAt(j) && cpuWord_letterflag[j] == 0){
                            switch (i) {
                                case 0: a5_l1.setBackground(Color.ORANGE);
                                break;
                                case 1: a5_l2.setBackground(Color.ORANGE);
                                break;
                                case 2: a5_l3.setBackground(Color.ORANGE);
                                break;
                                case 3: a5_l4.setBackground(Color.ORANGE);
                                break;
                            }
                            cpuWord_letterflag[j] = 1;
                            break;
                        }
                    }
                }
                u_Attempts--;
                User_input_confirm.setText("Finish");
                break;

                default:
                u_Score = 0;

                JOptionPane.showMessageDialog(null, "THE WORD IS: "+ cpuWord + " " + u_Score);
                break;
            }
            if(user_Input_Word.equalsIgnoreCase(cpuWord)){
                u_Score = ((u_Attempts+1)*2) * 100;
                frame_afterGame.setVisible(true);
                frame_afterGame.setSize(415,400);
                c3_text_Score.setText("Your score is: " + u_Score);
                u_Attempts = 0;
                
            }
        }

    }//GEN-LAST:event_User_input_confirmActionPerformed

    private void User_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_User_inputActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_User_inputActionPerformed

    private void nwgamebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nwgamebtnActionPerformed
        frame_afterGame.dispose();
        dispose();
        MainGame_Interface btn_reset = new MainGame_Interface();
        btn_reset.setVisible(true);
        
    }//GEN-LAST:event_nwgamebtnActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        frame_afterGame.dispose();
        dispose();
        MainGame_Menu btn_backGame_Menu = new MainGame_Menu();
        btn_backGame_Menu.setVisible(true);
    }//GEN-LAST:event_backbtnActionPerformed

    

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws FileNotFoundException{
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainGame_Interface().setVisible(true));
        
                
        
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField User_input;
    private javax.swing.JButton User_input_confirm;
    private javax.swing.JLabel a1_l1;
    private javax.swing.JLabel a1_l2;
    private javax.swing.JLabel a1_l3;
    private javax.swing.JLabel a1_l4;
    private javax.swing.JLabel a2_l1;
    private javax.swing.JLabel a2_l2;
    private javax.swing.JLabel a2_l3;
    private javax.swing.JLabel a2_l4;
    private javax.swing.JLabel a3_l1;
    private javax.swing.JLabel a3_l2;
    private javax.swing.JLabel a3_l3;
    private javax.swing.JLabel a3_l4;
    private javax.swing.JLabel a4_l1;
    private javax.swing.JLabel a4_l2;
    private javax.swing.JLabel a4_l3;
    private javax.swing.JLabel a4_l4;
    private javax.swing.JLabel a5_l1;
    private javax.swing.JLabel a5_l2;
    private javax.swing.JLabel a5_l3;
    private javax.swing.JLabel a5_l4;
    private javax.swing.JLabel attempt_Number;
    private javax.swing.JLabel back_Button;
    private javax.swing.JButton backbtn;
    private javax.swing.JLabel c1_text;
    private javax.swing.JLabel c2_text;
    private javax.swing.JLabel c3_text_Score;
    private javax.swing.JFrame frame_afterGame;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton nwgamebtn;
    private javax.swing.JLabel title_Game;
    // End of variables declaration//GEN-END:variables
}
