/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.two.player.wordle;

/**
 *
 * @author Joshua
 */
public class MainGame_Tutorial extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainGame_Tutorial.class.getName());

    /**
     * Creates new form MainGame_Tutorial
     */
    public MainGame_Tutorial() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        a1_l4 = new javax.swing.JLabel();
        a1_l1 = new javax.swing.JLabel();
        a1_l2 = new javax.swing.JLabel();
        a1_l3 = new javax.swing.JLabel();
        title_Game1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        a1_l5 = new javax.swing.JLabel();
        a1_l6 = new javax.swing.JLabel();
        a1_l7 = new javax.swing.JLabel();
        a1_l8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        a1_l9 = new javax.swing.JLabel();
        a1_l10 = new javax.swing.JLabel();
        a1_l11 = new javax.swing.JLabel();
        a1_l12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        a1_l13 = new javax.swing.JLabel();
        a1_l14 = new javax.swing.JLabel();
        a1_l15 = new javax.swing.JLabel();
        a1_l16 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        back_Button = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        a1_l4.setBackground(new java.awt.Color(240, 234, 214));
        a1_l4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a1_l4.setForeground(new java.awt.Color(30, 30, 30));
        a1_l4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a1_l4.setText("D");
        a1_l4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a1_l4.setOpaque(true);

        a1_l1.setBackground(new java.awt.Color(240, 234, 214));
        a1_l1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a1_l1.setForeground(new java.awt.Color(30, 30, 30));
        a1_l1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a1_l1.setText("W");
        a1_l1.setToolTipText("");
        a1_l1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a1_l1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        a1_l1.setInheritsPopupMenu(false);
        a1_l1.setOpaque(true);

        a1_l2.setBackground(new java.awt.Color(240, 234, 214));
        a1_l2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a1_l2.setForeground(new java.awt.Color(30, 30, 30));
        a1_l2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a1_l2.setText("O");
        a1_l2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a1_l2.setOpaque(true);

        a1_l3.setBackground(new java.awt.Color(240, 234, 214));
        a1_l3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a1_l3.setForeground(new java.awt.Color(30, 30, 30));
        a1_l3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a1_l3.setText("R");
        a1_l3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a1_l3.setOpaque(true);

        title_Game1.setFont(new java.awt.Font("Modern No. 20", 0, 36)); // NOI18N
        title_Game1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title_Game1.setText("WORDLE");

        jLabel1.setText("wordle is a simple word guessing game ");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Guess the secret word under 5 attempts");

        a1_l5.setBackground(new java.awt.Color(240, 234, 214));
        a1_l5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a1_l5.setForeground(new java.awt.Color(30, 30, 30));
        a1_l5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a1_l5.setText("R");
        a1_l5.setToolTipText("");
        a1_l5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a1_l5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        a1_l5.setInheritsPopupMenu(false);
        a1_l5.setOpaque(true);

        a1_l6.setBackground(new java.awt.Color(240, 234, 214));
        a1_l6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a1_l6.setForeground(new java.awt.Color(30, 30, 30));
        a1_l6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a1_l6.setText("O");
        a1_l6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a1_l6.setOpaque(true);

        a1_l7.setBackground(java.awt.Color.gray);
        a1_l7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a1_l7.setForeground(new java.awt.Color(30, 30, 30));
        a1_l7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a1_l7.setText("A");
        a1_l7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a1_l7.setOpaque(true);

        a1_l8.setBackground(new java.awt.Color(240, 234, 214));
        a1_l8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a1_l8.setForeground(new java.awt.Color(30, 30, 30));
        a1_l8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a1_l8.setText("D");
        a1_l8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a1_l8.setOpaque(true);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("A letter that is not present appears Gray");

        a1_l9.setBackground(java.awt.Color.orange);
        a1_l9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a1_l9.setForeground(new java.awt.Color(30, 30, 30));
        a1_l9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a1_l9.setText("R");
        a1_l9.setToolTipText("");
        a1_l9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a1_l9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        a1_l9.setInheritsPopupMenu(false);
        a1_l9.setOpaque(true);

        a1_l10.setBackground(new java.awt.Color(240, 234, 214));
        a1_l10.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a1_l10.setForeground(new java.awt.Color(30, 30, 30));
        a1_l10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a1_l10.setText("O");
        a1_l10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a1_l10.setOpaque(true);

        a1_l11.setBackground(java.awt.Color.gray);
        a1_l11.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a1_l11.setForeground(new java.awt.Color(30, 30, 30));
        a1_l11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a1_l11.setText("A");
        a1_l11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a1_l11.setOpaque(true);

        a1_l12.setBackground(new java.awt.Color(240, 234, 214));
        a1_l12.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a1_l12.setForeground(new java.awt.Color(30, 30, 30));
        a1_l12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a1_l12.setText("D");
        a1_l12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a1_l12.setOpaque(true);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("A letter that is  present appears Orange");

        a1_l13.setBackground(java.awt.Color.orange);
        a1_l13.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a1_l13.setForeground(new java.awt.Color(30, 30, 30));
        a1_l13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a1_l13.setText("R");
        a1_l13.setToolTipText("");
        a1_l13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a1_l13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        a1_l13.setInheritsPopupMenu(false);
        a1_l13.setOpaque(true);

        a1_l14.setBackground(java.awt.Color.green);
        a1_l14.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a1_l14.setForeground(new java.awt.Color(30, 30, 30));
        a1_l14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a1_l14.setText("O");
        a1_l14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a1_l14.setOpaque(true);

        a1_l15.setBackground(java.awt.Color.gray);
        a1_l15.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a1_l15.setForeground(new java.awt.Color(30, 30, 30));
        a1_l15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a1_l15.setText("A");
        a1_l15.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a1_l15.setOpaque(true);

        a1_l16.setBackground(java.awt.Color.green);
        a1_l16.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a1_l16.setForeground(new java.awt.Color(30, 30, 30));
        a1_l16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a1_l16.setText("D");
        a1_l16.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a1_l16.setOpaque(true);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("A letter that is correct appears Green");

        jButton1.setText("PLAY");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        back_Button.setText("<- Back");
        back_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back_ButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(back_Button)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(title_Game1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(a1_l13, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(a1_l14, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(a1_l15, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(a1_l16, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(a1_l9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(a1_l10, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(a1_l11, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(a1_l12, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(a1_l5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(a1_l6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(a1_l7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(a1_l8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(a1_l1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(a1_l2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(a1_l3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(a1_l4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))))))))
            .addGroup(layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(jButton1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(title_Game1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(back_Button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(a1_l1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a1_l2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(a1_l4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(a1_l3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(a1_l5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a1_l6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(a1_l8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(a1_l7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(a1_l9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a1_l10, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(a1_l12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(a1_l11, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(a1_l13, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a1_l14, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(a1_l16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(a1_l15, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void back_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_ButtonMouseClicked
        dispose();
        MainGame_Menu btn_back = new MainGame_Menu();
        btn_back.setVisible(true);
    }//GEN-LAST:event_back_ButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainGame_Tutorial().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel a1_l1;
    private javax.swing.JLabel a1_l10;
    private javax.swing.JLabel a1_l11;
    private javax.swing.JLabel a1_l12;
    private javax.swing.JLabel a1_l13;
    private javax.swing.JLabel a1_l14;
    private javax.swing.JLabel a1_l15;
    private javax.swing.JLabel a1_l16;
    private javax.swing.JLabel a1_l2;
    private javax.swing.JLabel a1_l3;
    private javax.swing.JLabel a1_l4;
    private javax.swing.JLabel a1_l5;
    private javax.swing.JLabel a1_l6;
    private javax.swing.JLabel a1_l7;
    private javax.swing.JLabel a1_l8;
    private javax.swing.JLabel a1_l9;
    private javax.swing.JLabel back_Button;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel title_Game1;
    // End of variables declaration//GEN-END:variables
}
