/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.two.player.wordle;

import java.awt.Color;
import javax.swing.JOptionPane;
import java.util.Scanner;
import java.util.Random;
import java.io.File;
import java.io.FileNotFoundException;
import java.lang.invoke.MethodHandles;

/**
 *
 * @author Joshua
 */
public class MainGame_Interface extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainGame_Interface.class.getName());

    /**
     * Creates new form MainGame_Interface
     */
    private int u_Attempts = 4;
    private String cpuWord = ""; // global variable for the cpu word 
    
    
    
    public MainGame_Interface() {
        initComponents();
        
        
        try {
            File fopen = new File("C:/Users/Joshua/Documents/NetBeansProjects/TWO-PLAYER-WORDLE/src/main/java/com/mycompany/two/player/wordle/words.txt");
            Scanner cpuScanner = new Scanner(fopen);        
        
            //random number generator for the word 
            Random word_Generator = new Random();
            int max = 100;
            int word_Generator_Index = word_Generator.nextInt(max);

            while(cpuScanner.hasNextLine()){
                for (int i = 0; i < word_Generator_Index-1; i++) {
                    cpuScanner.nextLine();
                }
                cpuWord = cpuScanner.nextLine();
                break;
            }
            cpuScanner.close();
        } catch (Exception FileNotException) {
            JOptionPane.showMessageDialog(null, "There was a problem in loading the Word Database");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        User_input = new javax.swing.JTextField();
        User_input_confirm = new javax.swing.JButton();
        a1_l4 = new javax.swing.JLabel();
        a1_l1 = new javax.swing.JLabel();
        a1_l2 = new javax.swing.JLabel();
        a1_l3 = new javax.swing.JLabel();
        a2_l1 = new javax.swing.JLabel();
        a2_l2 = new javax.swing.JLabel();
        a2_l3 = new javax.swing.JLabel();
        a2_l4 = new javax.swing.JLabel();
        a3_l1 = new javax.swing.JLabel();
        a3_l2 = new javax.swing.JLabel();
        a3_l3 = new javax.swing.JLabel();
        a3_l4 = new javax.swing.JLabel();
        a4_l1 = new javax.swing.JLabel();
        a4_l2 = new javax.swing.JLabel();
        a4_l3 = new javax.swing.JLabel();
        a4_l4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(240, 234, 214));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.white);

        User_input.setText("ENTER A 4 LETTER WORD");
        User_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                User_inputActionPerformed(evt);
            }
        });

        User_input_confirm.setText("Confirm");
        User_input_confirm.setBorder(new javax.swing.border.MatteBorder(null));
        User_input_confirm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        User_input_confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                User_input_confirmActionPerformed(evt);
            }
        });

        a1_l4.setBackground(new java.awt.Color(240, 234, 214));
        a1_l4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a1_l4.setForeground(new java.awt.Color(240, 234, 214));
        a1_l4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a1_l4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a1_l4.setOpaque(true);

        a1_l1.setBackground(new java.awt.Color(240, 234, 214));
        a1_l1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a1_l1.setForeground(new java.awt.Color(240, 234, 214));
        a1_l1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a1_l1.setToolTipText("");
        a1_l1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a1_l1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        a1_l1.setInheritsPopupMenu(false);
        a1_l1.setOpaque(true);

        a1_l2.setBackground(new java.awt.Color(240, 234, 214));
        a1_l2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a1_l2.setForeground(new java.awt.Color(240, 234, 214));
        a1_l2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a1_l2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a1_l2.setOpaque(true);

        a1_l3.setBackground(new java.awt.Color(240, 234, 214));
        a1_l3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a1_l3.setForeground(new java.awt.Color(240, 234, 214));
        a1_l3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a1_l3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a1_l3.setOpaque(true);

        a2_l1.setBackground(new java.awt.Color(240, 234, 214));
        a2_l1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a2_l1.setForeground(new java.awt.Color(240, 234, 214));
        a2_l1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a2_l1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a2_l1.setOpaque(true);

        a2_l2.setBackground(new java.awt.Color(240, 234, 214));
        a2_l2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a2_l2.setForeground(new java.awt.Color(240, 234, 214));
        a2_l2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a2_l2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a2_l2.setOpaque(true);

        a2_l3.setBackground(new java.awt.Color(240, 234, 214));
        a2_l3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a2_l3.setForeground(new java.awt.Color(240, 234, 214));
        a2_l3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a2_l3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a2_l3.setOpaque(true);

        a2_l4.setBackground(new java.awt.Color(240, 234, 214));
        a2_l4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a2_l4.setForeground(new java.awt.Color(240, 234, 214));
        a2_l4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a2_l4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a2_l4.setOpaque(true);

        a3_l1.setBackground(new java.awt.Color(240, 234, 214));
        a3_l1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a3_l1.setForeground(new java.awt.Color(240, 234, 214));
        a3_l1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a3_l1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a3_l1.setOpaque(true);

        a3_l2.setBackground(new java.awt.Color(240, 234, 214));
        a3_l2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a3_l2.setForeground(new java.awt.Color(240, 234, 214));
        a3_l2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a3_l2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a3_l2.setOpaque(true);

        a3_l3.setBackground(new java.awt.Color(240, 234, 214));
        a3_l3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a3_l3.setForeground(new java.awt.Color(240, 234, 214));
        a3_l3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a3_l3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a3_l3.setOpaque(true);

        a3_l4.setBackground(new java.awt.Color(240, 234, 214));
        a3_l4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a3_l4.setForeground(new java.awt.Color(240, 234, 214));
        a3_l4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a3_l4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a3_l4.setOpaque(true);

        a4_l1.setBackground(new java.awt.Color(240, 234, 214));
        a4_l1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a4_l1.setForeground(new java.awt.Color(240, 234, 214));
        a4_l1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a4_l1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a4_l1.setOpaque(true);

        a4_l2.setBackground(new java.awt.Color(240, 234, 214));
        a4_l2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a4_l2.setForeground(new java.awt.Color(240, 234, 214));
        a4_l2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a4_l2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a4_l2.setOpaque(true);

        a4_l3.setBackground(new java.awt.Color(240, 234, 214));
        a4_l3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a4_l3.setForeground(new java.awt.Color(240, 234, 214));
        a4_l3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a4_l3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a4_l3.setOpaque(true);

        a4_l4.setBackground(new java.awt.Color(240, 234, 214));
        a4_l4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        a4_l4.setForeground(new java.awt.Color(240, 234, 214));
        a4_l4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a4_l4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a4_l4.setOpaque(true);

        jLabel1.setFont(new java.awt.Font("Modern No. 20", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("WORDLE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(a3_l1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(a3_l2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(a3_l3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(a3_l4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(a2_l1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(a2_l2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(a2_l3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(a2_l4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(a1_l1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(a1_l2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(a1_l3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(a1_l4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(a4_l1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(a4_l2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(a4_l3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(a4_l4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(User_input, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(User_input_confirm, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(a1_l1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a1_l2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(a1_l4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(a1_l3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(a2_l1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a2_l2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(a2_l4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(a2_l3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(a3_l1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a3_l2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(a3_l4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(a3_l3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(a4_l1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a4_l2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(a4_l4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(a4_l3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(User_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(User_input_confirm, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void User_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_User_inputActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_User_inputActionPerformed
    
    
    
    private void User_input_confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_User_input_confirmActionPerformed
        String user_Input_Word  = "";
        user_Input_Word = User_input.getText().toLowerCase();
        
        String []Conv_user_Input_Word = user_Input_Word.split("");
        
        
        if(user_Input_Word.length() != 4){
            JOptionPane.showMessageDialog(null,"The word should be made of 4 Letters");
        } else {
        int []cpuWord_letterflag = {0,0,0,0};
        int []userInput_letterflag = {0,0,0,0};
            switch (u_Attempts) {
                case 4:
                    
                        a1_l1.setText(Conv_user_Input_Word[0]);
                        a1_l1.setBackground(Color.gray);
                            
                        a1_l2.setText(Conv_user_Input_Word[1]);
                        a1_l2.setBackground(Color.gray);
                        
                        a1_l3.setText(Conv_user_Input_Word[2]);
                        a1_l3.setBackground(Color.gray);
                        
                        a1_l4.setText(Conv_user_Input_Word[3]);
                        a1_l4.setBackground(Color.gray);
                        
                    for (int i = 0; i < 4; i++) {    
                        if(user_Input_Word.charAt(i) == cpuWord.charAt(i)){
                            switch (i) {
                                case 0: a1_l1.setBackground(Color.GREEN);
                                break;
                                case 1: a1_l2.setBackground(Color.GREEN);
                                break;
                                case 2: a1_l3.setBackground(Color.GREEN);
                                break;
                                case 3: a1_l4.setBackground(Color.GREEN);
                                break;
                            }
                            cpuWord_letterflag[i] = 1;
                            userInput_letterflag[i] = 1;
                        }
                    }
                    
                    for (int i = 0; i < 4; i++) {
                        if(userInput_letterflag[i] == 1){
                            continue;
                        }
                        for (int j = 0; j < 4; j++) {
                             if(user_Input_Word.charAt(i) == cpuWord.charAt(j) && cpuWord_letterflag[j] == 0){
                                switch (i) {
                                case 0: a1_l1.setBackground(Color.ORANGE);
                                break;
                                case 1: a1_l2.setBackground(Color.ORANGE);
                                break;
                                case 2: a1_l3.setBackground(Color.ORANGE);
                                break;
                                case 3: a1_l4.setBackground(Color.ORANGE);
                                break;
                                }
                                cpuWord_letterflag[j] = 1;
                                break;
                            }
                        }
                    }
                u_Attempts--;
                break;
                
                
                case 3:
                    
                        a2_l1.setText(Conv_user_Input_Word[0]);
                        a2_l1.setBackground(Color.gray);
                        
                        a2_l2.setText(Conv_user_Input_Word[1]);
                        a2_l2.setBackground(Color.gray);
                        
                        a2_l3.setText(Conv_user_Input_Word[2]);
                        a2_l3.setBackground(Color.gray);
                        
                        a2_l4.setText(Conv_user_Input_Word[3]);
                        a2_l4.setBackground(Color.gray);
                        
                    for (int i = 0; i < 4; i++) {
                        if(user_Input_Word.charAt(i) == cpuWord.charAt(i)){
                            switch (i) {
                                case 0: a2_l1.setBackground(Color.GREEN);
                                break;
                                case 1: a2_l2.setBackground(Color.GREEN);
                                break;
                                case 2: a2_l3.setBackground(Color.GREEN);
                                break;
                                case 3: a2_l4.setBackground(Color.GREEN);
                                break;
                            }
                            cpuWord_letterflag[i] = 1;
                            userInput_letterflag[i] = 1;
                        }
                    }
                    for (int i = 0; i < 4; i++) {
                        if(userInput_letterflag[i] == 1){
                            continue;
                        }
                        for (int j = 0; j < 4; j++) {
                             if(user_Input_Word.charAt(i) == cpuWord.charAt(j) && cpuWord_letterflag[j] == 0){
                                switch (i) {
                                case 0: a2_l1.setBackground(Color.ORANGE);
                                break;
                                case 1: a2_l2.setBackground(Color.ORANGE);
                                break;
                                case 2: a2_l3.setBackground(Color.ORANGE);
                                break;
                                case 3: a2_l4.setBackground(Color.ORANGE);
                                break;
                                }
                                cpuWord_letterflag[j] = 1;
                                break;
                            }
                        }
                    }
                u_Attempts--;
                break;
                
                
                case 2:
                    
                        a3_l1.setText(Conv_user_Input_Word[0]);
                        a3_l1.setBackground(Color.gray);
                        
                        a3_l2.setText(Conv_user_Input_Word[1]);
                        a3_l2.setBackground(Color.gray);
                        
                        a3_l3.setText(Conv_user_Input_Word[2]);
                        a3_l3.setBackground(Color.gray);
                        
                        a3_l4.setText(Conv_user_Input_Word[3]);
                        a3_l4.setBackground(Color.gray);
                        
                    for (int i = 0; i < 4; i++) {    
                        if(user_Input_Word.charAt(i) == cpuWord.charAt(i)){
                            switch (i) {
                                case 0: a3_l1.setBackground(Color.GREEN);
                                break;
                                case 1: a3_l2.setBackground(Color.GREEN);
                                break;
                                case 2: a3_l3.setBackground(Color.GREEN);
                                break;
                                case 3: a3_l4.setBackground(Color.GREEN);
                                break;
                            }
                            cpuWord_letterflag[i] = 1;
                            userInput_letterflag[i] = 1;
                        }
                    }
                    for (int i = 0; i < 4; i++) {
                        if(userInput_letterflag[i] == 1){
                            continue;
                        }
                        for (int j = 0; j < 4; j++) {
                             if(user_Input_Word.charAt(i) == cpuWord.charAt(j) && cpuWord_letterflag[j] == 0){
                                switch (i) {
                                case 0: a3_l1.setBackground(Color.ORANGE);
                                break;
                                case 1: a3_l2.setBackground(Color.ORANGE);
                                break;
                                case 2: a3_l3.setBackground(Color.ORANGE);
                                break;
                                case 3: a3_l4.setBackground(Color.ORANGE);
                                break;
                                }
                                cpuWord_letterflag[j] = 1;
                                break;
                            }
                        }
                    }
                u_Attempts--;
                break;
                
                case 1:
                    
                        a4_l1.setText(Conv_user_Input_Word[0]);
                        a4_l1.setBackground(Color.gray);
                        
                        a4_l2.setText(Conv_user_Input_Word[1]);
                        a4_l2.setBackground(Color.gray);
                        
                        a4_l3.setText(Conv_user_Input_Word[2]);
                        a4_l3.setBackground(Color.gray);
                        
                        a4_l4.setText(Conv_user_Input_Word[3]);
                        a4_l4.setBackground(Color.gray);
                        
                    for (int i = 0; i < 4; i++) {    
                        if(user_Input_Word.charAt(i) == cpuWord.charAt(i)){
                            switch (i) {
                                case 0: a4_l1.setBackground(Color.GREEN);
                                break;
                                case 1: a4_l2.setBackground(Color.GREEN);
                                break;
                                case 2: a4_l3.setBackground(Color.GREEN);
                                break;
                                case 3: a4_l4.setBackground(Color.GREEN);
                                break;
                            }
                            cpuWord_letterflag[i] = 1;
                            userInput_letterflag[i] = 1;
                        }
                    }
                    for (int i = 0; i < 4; i++) {
                        if(userInput_letterflag[i] == 1){
                            continue;
                        }
                        for (int j = 0; j < 4; j++) {
                             if(user_Input_Word.charAt(i) == cpuWord.charAt(j) && cpuWord_letterflag[j] == 0){
                                switch (i) {
                                case 0: a4_l1.setBackground(Color.ORANGE);
                                break;
                                case 1: a4_l2.setBackground(Color.ORANGE);
                                break;
                                case 2: a4_l3.setBackground(Color.ORANGE);
                                break;
                                case 3: a4_l4.setBackground(Color   .ORANGE);
                                break;
                                }
                                cpuWord_letterflag[j] = 1;
                                break;
                            }
                        }
                    }
                u_Attempts-=2;
                break;
                
                default:
                    JOptionPane.showMessageDialog(null, "There are no more attempts. But the word was " + cpuWord);
                break;
            }
            if(user_Input_Word.equalsIgnoreCase(cpuWord)){
                JOptionPane.showMessageDialog(null, "THE WORD IS "+ cpuWord);
                u_Attempts = 0;
            }
        }
        
        
        
       
   
       
        
      
        
    }//GEN-LAST:event_User_input_confirmActionPerformed

    

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws FileNotFoundException{
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainGame_Interface().setVisible(true));
        
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField User_input;
    private javax.swing.JButton User_input_confirm;
    private javax.swing.JLabel a1_l1;
    private javax.swing.JLabel a1_l2;
    private javax.swing.JLabel a1_l3;
    private javax.swing.JLabel a1_l4;
    private javax.swing.JLabel a2_l1;
    private javax.swing.JLabel a2_l2;
    private javax.swing.JLabel a2_l3;
    private javax.swing.JLabel a2_l4;
    private javax.swing.JLabel a3_l1;
    private javax.swing.JLabel a3_l2;
    private javax.swing.JLabel a3_l3;
    private javax.swing.JLabel a3_l4;
    private javax.swing.JLabel a4_l1;
    private javax.swing.JLabel a4_l2;
    private javax.swing.JLabel a4_l3;
    private javax.swing.JLabel a4_l4;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
