/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.two.player.wordle;

import javax.swing.JOptionPane;

/**
 *
 * @author Joshua
 */
public class MainGame_EnterUserWord extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainGame_EnterUserWord.class.getName());

    
    public String player1_word;
    public String player2_word;
    
    private boolean isPlayer1Turn = true;
   
    /**
     * Creates new form MainGame_FrameAfterGameL
     */
    public MainGame_EnterUserWord() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        back_Button2 = new javax.swing.JLabel();
        c1_text = new javax.swing.JLabel();
        c2_text = new javax.swing.JLabel();
        cnfrm_btn = new javax.swing.JButton();
        userInput = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(119, 136, 115));
        jPanel2.setForeground(new java.awt.Color(210, 220, 182));
        jPanel2.setMaximumSize(new java.awt.Dimension(400, 400));
        jPanel2.setMinimumSize(new java.awt.Dimension(400, 400));

        back_Button2.setForeground(new java.awt.Color(210, 220, 182));
        back_Button2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        back_Button2.setText("Back");
        back_Button2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back_Button2MouseClicked(evt);
            }
        });

        c1_text.setFont(new java.awt.Font("AirbusDisp2", 1, 14)); // NOI18N
        c1_text.setForeground(new java.awt.Color(210, 220, 182));
        c1_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        c1_text.setText("Enter a word");

        c2_text.setFont(new java.awt.Font("AirbusDisp2", 1, 14)); // NOI18N
        c2_text.setForeground(new java.awt.Color(210, 220, 182));
        c2_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        c2_text.setText("For player 1:");

        cnfrm_btn.setBackground(new java.awt.Color(210, 220, 182));
        cnfrm_btn.setForeground(new java.awt.Color(119, 136, 115));
        cnfrm_btn.setText("Confirm");
        cnfrm_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnfrm_btnActionPerformed(evt);
            }
        });

        userInput.setBackground(new java.awt.Color(241, 243, 224));
        userInput.setFont(new java.awt.Font("AirbusDisp2", 0, 12)); // NOI18N
        userInput.setForeground(new java.awt.Color(119, 136, 115));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(userInput, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(c1_text, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(c2_text, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                        .addGap(61, 61, 61))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(cnfrm_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(139, 139, 139))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(back_Button2)
                        .addGap(185, 185, 185))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(c1_text, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c2_text, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(userInput, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(cnfrm_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(back_Button2)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(416, 409));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cnfrm_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnfrm_btnActionPerformed
        String currentInput = userInput.getText().trim();
        
        if(currentInput.length() != 4){
            JOptionPane.showMessageDialog(null, "Word Must be made up of 4 letters");
            return;
        }
        if (isPlayer1Turn) {
            player1_word = currentInput;
            JOptionPane.showMessageDialog(null, "Player 1 Word Set!");
            
            userInput.setText("");
            c2_text.setText("For Player 2: ");
            isPlayer1Turn = false;
        } else {
            player2_word = currentInput;
            JOptionPane.showMessageDialog(null, "Player 2 Word Set!");
            
            dispose();
            MainGame_Versus sendWord = new MainGame_Versus(player1_word, player2_word);
            sendWord.setVisible(true);

        }
                

    }//GEN-LAST:event_cnfrm_btnActionPerformed

    private void back_Button2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_Button2MouseClicked
        dispose();
        MainGame_Menu btn_back = new MainGame_Menu();
        btn_back.setVisible(true);
    }//GEN-LAST:event_back_Button2MouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainGame_EnterUserWord().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back_Button;
    private javax.swing.JLabel back_Button1;
    private javax.swing.JLabel back_Button2;
    private javax.swing.JLabel c1_text;
    private javax.swing.JLabel c2_text;
    private javax.swing.JButton cnfrm_btn;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextPane userInput;
    // End of variables declaration//GEN-END:variables
}
